/* tslint:disable */
/* eslint-disable */
/**
 * Mezcala API
 * API for managing databases via Mezcala.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CheckHealth200Response {
    'status': string;
    'version'?: string;
}
/**
 * Task status for a `createDatabase` operation. On completion, `result` contains the new database ID. 
 */
export interface CreateDatabaseTaskStatus {
    'task_id': string;
    'status': CreateDatabaseTaskStatusStatusEnum;
    'created_at': string;
    'completed_at'?: string;
    /**
     * Human-readable status message
     */
    'message'?: string;
    'error'?: Error;
    'result'?: DatabaseAcknowledgment;
}

export const CreateDatabaseTaskStatusStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type CreateDatabaseTaskStatusStatusEnum = typeof CreateDatabaseTaskStatusStatusEnum[keyof typeof CreateDatabaseTaskStatusStatusEnum];

export interface CreateSyncRule201Response {
    /**
     * Source database ID registered in Mezcala
     */
    'from': number;
    /**
     * Destination database ID registered in Mezcala
     */
    'to': number;
    /**
     * Table names to exclude from the sync
     */
    'exclude'?: Array<string>;
    /**
     * Schemas to include in the sync
     */
    'schemas'?: Array<string>;
    /**
     * Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely. 
     */
    'data_rules'?: { [key: string]: string; };
    /**
     * System-assigned sync rule identifier
     */
    'id': number;
}
/**
 * Confirmation returned after a database is successfully created or registered. Contains only the system-assigned ID. 
 */
export interface DatabaseAcknowledgment {
    /**
     * System-assigned unique identifier for the new database
     */
    'id': number;
    'message': string;
}
/**
 * Connection configuration for a database.
 */
export interface DatabaseConfig {
    'name'?: string;
    'username': string;
    'password': string;
    'engine': string;
    'version'?: string;
    /**
     * Optional human-friendly label
     */
    'alias'?: string;
    'host': string;
    'port': string;
    'ssl_mode'?: string;
    /**
     * Optional filesystem path for local/embedded engines
     */
    'path'?: string;
    /**
     * Database role for connection
     */
    'role'?: string;
    /**
     * The docker image to use
     */
    'image'?: string;
}
/**
 * Task status for a `deleteDatabase` operation. On completion, `result` contains a deletion confirmation. 
 */
export interface DeleteDatabaseTaskStatus {
    'task_id': string;
    'status': DeleteDatabaseTaskStatusStatusEnum;
    'created_at': string;
    'completed_at'?: string;
    /**
     * Human-readable status message
     */
    'message'?: string;
    'error'?: Error;
    'result'?: DeletionAcknowledgment;
}

export const DeleteDatabaseTaskStatusStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type DeleteDatabaseTaskStatusStatusEnum = typeof DeleteDatabaseTaskStatusStatusEnum[keyof typeof DeleteDatabaseTaskStatusStatusEnum];

/**
 * Confirmation that a resource was deleted.
 */
export interface DeletionAcknowledgment {
    'message': string;
}
export interface ExecuteSyncRuleRequest {
    /**
     * ID of the sync rule to execute
     */
    'id': number;
}
/**
 * Task status for an `executeSyncRule` operation. On completion, `result` contains sync timing and outcome details. 
 */
export interface ExecuteSyncTaskStatus {
    'task_id': string;
    'status': ExecuteSyncTaskStatusStatusEnum;
    'created_at': string;
    'completed_at'?: string;
    /**
     * Human-readable status message
     */
    'message'?: string;
    'error'?: Error;
    'result'?: SyncExecutionResult;
}

export const ExecuteSyncTaskStatusStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type ExecuteSyncTaskStatusStatusEnum = typeof ExecuteSyncTaskStatusStatusEnum[keyof typeof ExecuteSyncTaskStatusStatusEnum];

export interface GetDatabaseConnectionUrl200Response {
    /**
     * Database ID
     */
    'id': number;
    /**
     * Fully-formed connection URL including credentials. Treat as a secret. 
     */
    'connection_url': string;
}
export interface GetSupportedEngines200ResponseInner {
    'engine': string;
    'versions': Array<string>;
}
/**
 * Standard error envelope returned for all 4xx and 5xx responses.
 */
export interface ModelError {
    /**
     * Machine-readable error code
     */
    'code': string;
    /**
     * Human-readable description of the error
     */
    'message': string;
    /**
     * Optional additional context about the error
     */
    'details'?: { [key: string]: any; };
}
/**
 * Outcome details of a sync rule execution.
 */
export interface SyncExecutionResult {
    'sync_id': number;
    'status': string;
    'started_at'?: string;
    'finished_at'?: string;
    /**
     * Number of tables processed during the sync
     */
    'tables_synced'?: number;
    /**
     * Total number of rows written to the destination
     */
    'rows_synced'?: number;
    'message'?: string;
}
/**
 * Configuration for syncing data between databases with optional masking rules.
 */
export interface SyncRuleConfig {
    /**
     * Source database ID registered in Mezcala
     */
    'from': number;
    /**
     * Destination database ID registered in Mezcala
     */
    'to': number;
    /**
     * Table names to exclude from the sync
     */
    'exclude'?: Array<string>;
    /**
     * Schemas to include in the sync
     */
    'schemas'?: Array<string>;
    /**
     * Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely. 
     */
    'data_rules'?: { [key: string]: string; };
}
/**
 * Returned immediately when an async operation is accepted.
 */
export interface TaskReference {
    /**
     * Unique identifier for the async task
     */
    'task_id': string;
}
/**
 * Common fields shared by all task status responses. When `status` is `completed` the operation-specific `result` field is populated. When `status` is `failed` the `error` field is populated. 
 */
export interface TaskStatusBase {
    'task_id': string;
    'status': TaskStatusBaseStatusEnum;
    'created_at': string;
    'completed_at'?: string;
    /**
     * Human-readable status message
     */
    'message'?: string;
    'error'?: Error;
}

export const TaskStatusBaseStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type TaskStatusBaseStatusEnum = typeof TaskStatusBaseStatusEnum[keyof typeof TaskStatusBaseStatusEnum];


/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Synchronously registers an external database connection and returns an acknowledgment with the assigned database ID. 
         * @summary Register an existing external database
         * @param {DatabaseConfig} databaseConfig Payload for registering or creating a database connection.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addDatabase: async (databaseConfig: DatabaseConfig, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'databaseConfig' is not null or undefined
            assertParamExists('addDatabase', 'databaseConfig', databaseConfig)
            const localVarPath = `/databases/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(databaseConfig, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Check Mezcala health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Initiates database creation asynchronously. Returns a task ID that can be polled via `GET /databases/create/tasks/{taskID}`. On completion the task result contains an acknowledgment with the new database ID. 
         * @summary Create a new managed database
         * @param {DatabaseConfig} databaseConfig Payload for registering or creating a database connection.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDatabase: async (databaseConfig: DatabaseConfig, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'databaseConfig' is not null or undefined
            assertParamExists('createDatabase', 'databaseConfig', databaseConfig)
            const localVarPath = `/databases/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(databaseConfig, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Synchronously creates a sync rule and returns it with its assigned ID. 
         * @summary Create a new sync rule for a database
         * @param {number} dbID Unique identifier of the database
         * @param {SyncRuleConfig} syncRuleConfig Payload for creating or updating a sync rule.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSyncRule: async (dbID: number, syncRuleConfig: SyncRuleConfig, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbID' is not null or undefined
            assertParamExists('createSyncRule', 'dbID', dbID)
            // verify required parameter 'syncRuleConfig' is not null or undefined
            assertParamExists('createSyncRule', 'syncRuleConfig', syncRuleConfig)
            const localVarPath = `/databases/{dbID}/sync/init`
                .replace(`{${"dbID"}}`, encodeURIComponent(String(dbID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(syncRuleConfig, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Initiates database deletion asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/delete/tasks/{taskID}`. On completion the task result contains a confirmation message. 
         * @summary Delete a database by ID
         * @param {number} dbID Unique identifier of the database
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDatabase: async (dbID: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbID' is not null or undefined
            assertParamExists('deleteDatabase', 'dbID', dbID)
            const localVarPath = `/databases/{dbID}/delete`
                .replace(`{${"dbID"}}`, encodeURIComponent(String(dbID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Synchronously deletes a sync rule.
         * @summary Delete a sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSyncRule: async (dbID: number, syncID: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbID' is not null or undefined
            assertParamExists('deleteSyncRule', 'dbID', dbID)
            // verify required parameter 'syncID' is not null or undefined
            assertParamExists('deleteSyncRule', 'syncID', syncID)
            const localVarPath = `/databases/{dbID}/sync/{syncID}/delete`
                .replace(`{${"dbID"}}`, encodeURIComponent(String(dbID)))
                .replace(`{${"syncID"}}`, encodeURIComponent(String(syncID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Triggers a sync rule run asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/sync/{syncID}/tasks/{taskID}`. On completion the task result contains the sync execution summary. 
         * @summary Trigger execution of a sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {ExecuteSyncRuleRequest} executeSyncRuleRequest Identifies which sync rule to execute.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeSyncRule: async (dbID: number, executeSyncRuleRequest: ExecuteSyncRuleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbID' is not null or undefined
            assertParamExists('executeSyncRule', 'dbID', dbID)
            // verify required parameter 'executeSyncRuleRequest' is not null or undefined
            assertParamExists('executeSyncRule', 'executeSyncRuleRequest', executeSyncRuleRequest)
            const localVarPath = `/databases/{dbID}/sync`
                .replace(`{${"dbID"}}`, encodeURIComponent(String(dbID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(executeSyncRuleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Polls the status of a task initiated by `POST /databases/create`. When `status` is `completed` the `result` field contains a `DatabaseAcknowledgment` with the new database ID. 
         * @summary Get the status of a createDatabase task
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCreateDatabaseTaskStatus: async (taskID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskID' is not null or undefined
            assertParamExists('getCreateDatabaseTaskStatus', 'taskID', taskID)
            const localVarPath = `/databases/create/tasks/{taskID}`
                .replace(`{${"taskID"}}`, encodeURIComponent(String(taskID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the fully-formed connection URL for the specified database, including credentials. Handle with care — treat the response as a secret. 
         * @summary Get the connection URL for a database
         * @param {number} dbID Unique identifier of the database
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDatabaseConnectionUrl: async (dbID: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbID' is not null or undefined
            assertParamExists('getDatabaseConnectionUrl', 'dbID', dbID)
            const localVarPath = `/databases/{dbID}/connection-url`
                .replace(`{${"dbID"}}`, encodeURIComponent(String(dbID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Polls the status of a task initiated by `DELETE /databases/{dbID}/delete`. When `status` is `completed` the `result` field contains a `DeletionAcknowledgment`. 
         * @summary Get the status of a deleteDatabase task
         * @param {number} dbID Unique identifier of the database
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeleteDatabaseTaskStatus: async (dbID: number, taskID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbID' is not null or undefined
            assertParamExists('getDeleteDatabaseTaskStatus', 'dbID', dbID)
            // verify required parameter 'taskID' is not null or undefined
            assertParamExists('getDeleteDatabaseTaskStatus', 'taskID', taskID)
            const localVarPath = `/databases/{dbID}/delete/tasks/{taskID}`
                .replace(`{${"dbID"}}`, encodeURIComponent(String(dbID)))
                .replace(`{${"taskID"}}`, encodeURIComponent(String(taskID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Polls the status of a task initiated by `PUT /databases/{dbID}/sync`. When `status` is `completed` the `result` field contains a `SyncExecutionResult` with timing and outcome details. 
         * @summary Get the status of an executeSyncRule task
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecuteSyncTaskStatus: async (dbID: number, syncID: number, taskID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbID' is not null or undefined
            assertParamExists('getExecuteSyncTaskStatus', 'dbID', dbID)
            // verify required parameter 'syncID' is not null or undefined
            assertParamExists('getExecuteSyncTaskStatus', 'syncID', syncID)
            // verify required parameter 'taskID' is not null or undefined
            assertParamExists('getExecuteSyncTaskStatus', 'taskID', taskID)
            const localVarPath = `/databases/{dbID}/sync/{syncID}/tasks/{taskID}`
                .replace(`{${"dbID"}}`, encodeURIComponent(String(dbID)))
                .replace(`{${"syncID"}}`, encodeURIComponent(String(syncID)))
                .replace(`{${"taskID"}}`, encodeURIComponent(String(taskID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all supported database engines and versions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSupportedEngines: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/databases/supported`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Synchronously updates a sync rule and returns the updated record. 
         * @summary Update an existing sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {SyncRuleConfig} syncRuleConfig Payload for creating or updating a sync rule.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSyncRule: async (dbID: number, syncID: number, syncRuleConfig: SyncRuleConfig, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbID' is not null or undefined
            assertParamExists('updateSyncRule', 'dbID', dbID)
            // verify required parameter 'syncID' is not null or undefined
            assertParamExists('updateSyncRule', 'syncID', syncID)
            // verify required parameter 'syncRuleConfig' is not null or undefined
            assertParamExists('updateSyncRule', 'syncRuleConfig', syncRuleConfig)
            const localVarPath = `/databases/{dbID}/sync/{syncID}/update`
                .replace(`{${"dbID"}}`, encodeURIComponent(String(dbID)))
                .replace(`{${"syncID"}}`, encodeURIComponent(String(syncID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(syncRuleConfig, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Synchronously registers an external database connection and returns an acknowledgment with the assigned database ID. 
         * @summary Register an existing external database
         * @param {DatabaseConfig} databaseConfig Payload for registering or creating a database connection.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addDatabase(databaseConfig: DatabaseConfig, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DatabaseAcknowledgment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addDatabase(databaseConfig, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addDatabase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Check Mezcala health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckHealth200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.checkHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Initiates database creation asynchronously. Returns a task ID that can be polled via `GET /databases/create/tasks/{taskID}`. On completion the task result contains an acknowledgment with the new database ID. 
         * @summary Create a new managed database
         * @param {DatabaseConfig} databaseConfig Payload for registering or creating a database connection.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDatabase(databaseConfig: DatabaseConfig, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskReference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDatabase(databaseConfig, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createDatabase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Synchronously creates a sync rule and returns it with its assigned ID. 
         * @summary Create a new sync rule for a database
         * @param {number} dbID Unique identifier of the database
         * @param {SyncRuleConfig} syncRuleConfig Payload for creating or updating a sync rule.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSyncRule(dbID: number, syncRuleConfig: SyncRuleConfig, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateSyncRule201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSyncRule(dbID, syncRuleConfig, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createSyncRule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Initiates database deletion asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/delete/tasks/{taskID}`. On completion the task result contains a confirmation message. 
         * @summary Delete a database by ID
         * @param {number} dbID Unique identifier of the database
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDatabase(dbID: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskReference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDatabase(dbID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteDatabase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Synchronously deletes a sync rule.
         * @summary Delete a sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSyncRule(dbID: number, syncID: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSyncRule(dbID, syncID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteSyncRule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Triggers a sync rule run asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/sync/{syncID}/tasks/{taskID}`. On completion the task result contains the sync execution summary. 
         * @summary Trigger execution of a sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {ExecuteSyncRuleRequest} executeSyncRuleRequest Identifies which sync rule to execute.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async executeSyncRule(dbID: number, executeSyncRuleRequest: ExecuteSyncRuleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskReference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.executeSyncRule(dbID, executeSyncRuleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.executeSyncRule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Polls the status of a task initiated by `POST /databases/create`. When `status` is `completed` the `result` field contains a `DatabaseAcknowledgment` with the new database ID. 
         * @summary Get the status of a createDatabase task
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCreateDatabaseTaskStatus(taskID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDatabaseTaskStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCreateDatabaseTaskStatus(taskID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getCreateDatabaseTaskStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the fully-formed connection URL for the specified database, including credentials. Handle with care — treat the response as a secret. 
         * @summary Get the connection URL for a database
         * @param {number} dbID Unique identifier of the database
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDatabaseConnectionUrl(dbID: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetDatabaseConnectionUrl200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDatabaseConnectionUrl(dbID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getDatabaseConnectionUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Polls the status of a task initiated by `DELETE /databases/{dbID}/delete`. When `status` is `completed` the `result` field contains a `DeletionAcknowledgment`. 
         * @summary Get the status of a deleteDatabase task
         * @param {number} dbID Unique identifier of the database
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDeleteDatabaseTaskStatus(dbID: number, taskID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteDatabaseTaskStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDeleteDatabaseTaskStatus(dbID, taskID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getDeleteDatabaseTaskStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Polls the status of a task initiated by `PUT /databases/{dbID}/sync`. When `status` is `completed` the `result` field contains a `SyncExecutionResult` with timing and outcome details. 
         * @summary Get the status of an executeSyncRule task
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExecuteSyncTaskStatus(dbID: number, syncID: number, taskID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExecuteSyncTaskStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExecuteSyncTaskStatus(dbID, syncID, taskID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getExecuteSyncTaskStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all supported database engines and versions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSupportedEngines(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetSupportedEngines200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSupportedEngines(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSupportedEngines']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Synchronously updates a sync rule and returns the updated record. 
         * @summary Update an existing sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {SyncRuleConfig} syncRuleConfig Payload for creating or updating a sync rule.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSyncRule(dbID: number, syncID: number, syncRuleConfig: SyncRuleConfig, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateSyncRule201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSyncRule(dbID, syncID, syncRuleConfig, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateSyncRule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Synchronously registers an external database connection and returns an acknowledgment with the assigned database ID. 
         * @summary Register an existing external database
         * @param {DatabaseConfig} databaseConfig Payload for registering or creating a database connection.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addDatabase(databaseConfig: DatabaseConfig, options?: RawAxiosRequestConfig): AxiosPromise<DatabaseAcknowledgment> {
            return localVarFp.addDatabase(databaseConfig, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Check Mezcala health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkHealth(options?: RawAxiosRequestConfig): AxiosPromise<CheckHealth200Response> {
            return localVarFp.checkHealth(options).then((request) => request(axios, basePath));
        },
        /**
         * Initiates database creation asynchronously. Returns a task ID that can be polled via `GET /databases/create/tasks/{taskID}`. On completion the task result contains an acknowledgment with the new database ID. 
         * @summary Create a new managed database
         * @param {DatabaseConfig} databaseConfig Payload for registering or creating a database connection.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDatabase(databaseConfig: DatabaseConfig, options?: RawAxiosRequestConfig): AxiosPromise<TaskReference> {
            return localVarFp.createDatabase(databaseConfig, options).then((request) => request(axios, basePath));
        },
        /**
         * Synchronously creates a sync rule and returns it with its assigned ID. 
         * @summary Create a new sync rule for a database
         * @param {number} dbID Unique identifier of the database
         * @param {SyncRuleConfig} syncRuleConfig Payload for creating or updating a sync rule.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSyncRule(dbID: number, syncRuleConfig: SyncRuleConfig, options?: RawAxiosRequestConfig): AxiosPromise<CreateSyncRule201Response> {
            return localVarFp.createSyncRule(dbID, syncRuleConfig, options).then((request) => request(axios, basePath));
        },
        /**
         * Initiates database deletion asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/delete/tasks/{taskID}`. On completion the task result contains a confirmation message. 
         * @summary Delete a database by ID
         * @param {number} dbID Unique identifier of the database
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDatabase(dbID: number, options?: RawAxiosRequestConfig): AxiosPromise<TaskReference> {
            return localVarFp.deleteDatabase(dbID, options).then((request) => request(axios, basePath));
        },
        /**
         * Synchronously deletes a sync rule.
         * @summary Delete a sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSyncRule(dbID: number, syncID: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSyncRule(dbID, syncID, options).then((request) => request(axios, basePath));
        },
        /**
         * Triggers a sync rule run asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/sync/{syncID}/tasks/{taskID}`. On completion the task result contains the sync execution summary. 
         * @summary Trigger execution of a sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {ExecuteSyncRuleRequest} executeSyncRuleRequest Identifies which sync rule to execute.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeSyncRule(dbID: number, executeSyncRuleRequest: ExecuteSyncRuleRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaskReference> {
            return localVarFp.executeSyncRule(dbID, executeSyncRuleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Polls the status of a task initiated by `POST /databases/create`. When `status` is `completed` the `result` field contains a `DatabaseAcknowledgment` with the new database ID. 
         * @summary Get the status of a createDatabase task
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCreateDatabaseTaskStatus(taskID: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateDatabaseTaskStatus> {
            return localVarFp.getCreateDatabaseTaskStatus(taskID, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the fully-formed connection URL for the specified database, including credentials. Handle with care — treat the response as a secret. 
         * @summary Get the connection URL for a database
         * @param {number} dbID Unique identifier of the database
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDatabaseConnectionUrl(dbID: number, options?: RawAxiosRequestConfig): AxiosPromise<GetDatabaseConnectionUrl200Response> {
            return localVarFp.getDatabaseConnectionUrl(dbID, options).then((request) => request(axios, basePath));
        },
        /**
         * Polls the status of a task initiated by `DELETE /databases/{dbID}/delete`. When `status` is `completed` the `result` field contains a `DeletionAcknowledgment`. 
         * @summary Get the status of a deleteDatabase task
         * @param {number} dbID Unique identifier of the database
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeleteDatabaseTaskStatus(dbID: number, taskID: string, options?: RawAxiosRequestConfig): AxiosPromise<DeleteDatabaseTaskStatus> {
            return localVarFp.getDeleteDatabaseTaskStatus(dbID, taskID, options).then((request) => request(axios, basePath));
        },
        /**
         * Polls the status of a task initiated by `PUT /databases/{dbID}/sync`. When `status` is `completed` the `result` field contains a `SyncExecutionResult` with timing and outcome details. 
         * @summary Get the status of an executeSyncRule task
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {string} taskID Unique identifier of the async task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecuteSyncTaskStatus(dbID: number, syncID: number, taskID: string, options?: RawAxiosRequestConfig): AxiosPromise<ExecuteSyncTaskStatus> {
            return localVarFp.getExecuteSyncTaskStatus(dbID, syncID, taskID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all supported database engines and versions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSupportedEngines(options?: RawAxiosRequestConfig): AxiosPromise<Array<GetSupportedEngines200ResponseInner>> {
            return localVarFp.getSupportedEngines(options).then((request) => request(axios, basePath));
        },
        /**
         * Synchronously updates a sync rule and returns the updated record. 
         * @summary Update an existing sync rule
         * @param {number} dbID Unique identifier of the database
         * @param {number} syncID Unique identifier of the sync rule
         * @param {SyncRuleConfig} syncRuleConfig Payload for creating or updating a sync rule.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSyncRule(dbID: number, syncID: number, syncRuleConfig: SyncRuleConfig, options?: RawAxiosRequestConfig): AxiosPromise<CreateSyncRule201Response> {
            return localVarFp.updateSyncRule(dbID, syncID, syncRuleConfig, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * Synchronously registers an external database connection and returns an acknowledgment with the assigned database ID. 
     * @summary Register an existing external database
     * @param {DatabaseConfig} databaseConfig Payload for registering or creating a database connection.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addDatabase(databaseConfig: DatabaseConfig, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addDatabase(databaseConfig, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Check Mezcala health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public checkHealth(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).checkHealth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Initiates database creation asynchronously. Returns a task ID that can be polled via `GET /databases/create/tasks/{taskID}`. On completion the task result contains an acknowledgment with the new database ID. 
     * @summary Create a new managed database
     * @param {DatabaseConfig} databaseConfig Payload for registering or creating a database connection.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDatabase(databaseConfig: DatabaseConfig, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createDatabase(databaseConfig, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Synchronously creates a sync rule and returns it with its assigned ID. 
     * @summary Create a new sync rule for a database
     * @param {number} dbID Unique identifier of the database
     * @param {SyncRuleConfig} syncRuleConfig Payload for creating or updating a sync rule.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSyncRule(dbID: number, syncRuleConfig: SyncRuleConfig, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createSyncRule(dbID, syncRuleConfig, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Initiates database deletion asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/delete/tasks/{taskID}`. On completion the task result contains a confirmation message. 
     * @summary Delete a database by ID
     * @param {number} dbID Unique identifier of the database
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDatabase(dbID: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteDatabase(dbID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Synchronously deletes a sync rule.
     * @summary Delete a sync rule
     * @param {number} dbID Unique identifier of the database
     * @param {number} syncID Unique identifier of the sync rule
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSyncRule(dbID: number, syncID: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteSyncRule(dbID, syncID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Triggers a sync rule run asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/sync/{syncID}/tasks/{taskID}`. On completion the task result contains the sync execution summary. 
     * @summary Trigger execution of a sync rule
     * @param {number} dbID Unique identifier of the database
     * @param {ExecuteSyncRuleRequest} executeSyncRuleRequest Identifies which sync rule to execute.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public executeSyncRule(dbID: number, executeSyncRuleRequest: ExecuteSyncRuleRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).executeSyncRule(dbID, executeSyncRuleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Polls the status of a task initiated by `POST /databases/create`. When `status` is `completed` the `result` field contains a `DatabaseAcknowledgment` with the new database ID. 
     * @summary Get the status of a createDatabase task
     * @param {string} taskID Unique identifier of the async task
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCreateDatabaseTaskStatus(taskID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getCreateDatabaseTaskStatus(taskID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the fully-formed connection URL for the specified database, including credentials. Handle with care — treat the response as a secret. 
     * @summary Get the connection URL for a database
     * @param {number} dbID Unique identifier of the database
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDatabaseConnectionUrl(dbID: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getDatabaseConnectionUrl(dbID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Polls the status of a task initiated by `DELETE /databases/{dbID}/delete`. When `status` is `completed` the `result` field contains a `DeletionAcknowledgment`. 
     * @summary Get the status of a deleteDatabase task
     * @param {number} dbID Unique identifier of the database
     * @param {string} taskID Unique identifier of the async task
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDeleteDatabaseTaskStatus(dbID: number, taskID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getDeleteDatabaseTaskStatus(dbID, taskID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Polls the status of a task initiated by `PUT /databases/{dbID}/sync`. When `status` is `completed` the `result` field contains a `SyncExecutionResult` with timing and outcome details. 
     * @summary Get the status of an executeSyncRule task
     * @param {number} dbID Unique identifier of the database
     * @param {number} syncID Unique identifier of the sync rule
     * @param {string} taskID Unique identifier of the async task
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getExecuteSyncTaskStatus(dbID: number, syncID: number, taskID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getExecuteSyncTaskStatus(dbID, syncID, taskID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all supported database engines and versions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSupportedEngines(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSupportedEngines(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Synchronously updates a sync rule and returns the updated record. 
     * @summary Update an existing sync rule
     * @param {number} dbID Unique identifier of the database
     * @param {number} syncID Unique identifier of the sync rule
     * @param {SyncRuleConfig} syncRuleConfig Payload for creating or updating a sync rule.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSyncRule(dbID: number, syncID: number, syncRuleConfig: SyncRuleConfig, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateSyncRule(dbID, syncID, syncRuleConfig, options).then((request) => request(this.axios, this.basePath));
    }
}



