/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Mezcala health */
        get: operations["checkHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/supported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all supported database engines and versions */
        get: operations["getSupportedEngines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new managed database
         * @description Initiates database creation asynchronously. Returns a task ID that can be polled via `GET /databases/create/tasks/{taskID}`. On completion the task result contains an acknowledgment with the new database ID.
         */
        post: operations["createDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/create/tasks/{taskID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of a createDatabase task
         * @description Polls the status of a task initiated by `POST /databases/create`. When `status` is `completed` the `result` field contains a `DatabaseAcknowledgment` with the new database ID.
         */
        get: operations["getCreateDatabaseTaskStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an existing external database
         * @description Synchronously registers an external database connection and returns an acknowledgment with the assigned database ID.
         */
        post: operations["addDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{dbID}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a database by ID
         * @description Initiates database deletion asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/delete/tasks/{taskID}`. On completion the task result contains a confirmation message.
         */
        delete: operations["deleteDatabase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{dbID}/delete/tasks/{taskID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of a deleteDatabase task
         * @description Polls the status of a task initiated by `DELETE /databases/{dbID}/delete`. When `status` is `completed` the `result` field contains a `DeletionAcknowledgment`.
         */
        get: operations["getDeleteDatabaseTaskStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{dbID}/connection-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the connection URL for a database
         * @description Returns the fully-formed connection URL for the specified database, including credentials. Handle with care — treat the response as a secret.
         */
        get: operations["getDatabaseConnectionUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{dbID}/sync/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new sync rule for a database
         * @description Synchronously creates a sync rule and returns it with its assigned ID.
         */
        post: operations["createSyncRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{dbID}/sync/{syncID}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update an existing sync rule
         * @description Synchronously updates a sync rule and returns the updated record.
         */
        put: operations["updateSyncRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{dbID}/sync/{syncID}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a sync rule
         * @description Synchronously deletes a sync rule.
         */
        delete: operations["deleteSyncRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{dbID}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Trigger execution of a sync rule
         * @description Triggers a sync rule run asynchronously. Returns a task ID that can be polled via `GET /databases/{dbID}/sync/{syncID}/tasks/{taskID}`. On completion the task result contains the sync execution summary.
         */
        put: operations["executeSyncRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{dbID}/sync/{syncID}/tasks/{taskID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of an executeSyncRule task
         * @description Polls the status of a task initiated by `PUT /databases/{dbID}/sync`. When `status` is `completed` the `result` field contains a `SyncExecutionResult` with timing and outcome details.
         */
        get: operations["getExecuteSyncTaskStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error envelope returned for all 4xx and 5xx responses. */
        Error: {
            /**
             * @description Machine-readable error code
             * @example NOT_FOUND
             */
            code: string;
            /**
             * @description Human-readable description of the error
             * @example The requested resource was not found.
             */
            message: string;
            /** @description Optional additional context about the error */
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description Returned immediately when an async operation is accepted. */
        TaskReference: {
            /**
             * Format: uuid
             * @description Unique identifier for the async task
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            task_id: string;
        };
        /** @description Common fields shared by all task status responses. When `status` is `completed` the operation-specific `result` field is populated. When `status` is `failed` the `error` field is populated. */
        TaskStatusBase: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            task_id: string;
            /**
             * @example completed
             * @enum {string}
             */
            status: "pending" | "in_progress" | "completed" | "failed";
            /**
             * Format: date-time
             * @example 2024-06-01T12:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2024-06-01T12:00:05Z
             */
            completed_at?: string;
            /**
             * @description Human-readable status message
             * @example Task completed successfully.
             */
            message?: string;
            error?: components["schemas"]["Error"];
        };
        /** @description Task status for a `createDatabase` operation. On completion, `result` contains the new database ID. */
        CreateDatabaseTaskStatus: components["schemas"]["TaskStatusBase"] & {
            result?: components["schemas"]["DatabaseAcknowledgment"];
        };
        /** @description Task status for a `deleteDatabase` operation. On completion, `result` contains a deletion confirmation. */
        DeleteDatabaseTaskStatus: components["schemas"]["TaskStatusBase"] & {
            result?: components["schemas"]["DeletionAcknowledgment"];
        };
        /** @description Task status for an `executeSyncRule` operation. On completion, `result` contains sync timing and outcome details. */
        ExecuteSyncTaskStatus: components["schemas"]["TaskStatusBase"] & {
            result?: components["schemas"]["SyncExecutionResult"];
        };
        /** @description Connection configuration for a database. */
        DatabaseConfig: {
            /** @example my-database */
            name?: string;
            /** @example admin */
            username: string;
            /**
             * Format: password
             * @example s3cr3t
             */
            password: string;
            /** @example postgres */
            engine: string;
            /** @example 15 */
            version?: string;
            /**
             * @description Optional human-friendly label
             * @example prod-db
             */
            alias?: string;
            /** @example db.example.com */
            host: string;
            /** @example 5432 */
            port: string;
            /** @example require */
            ssl_mode?: string;
            /**
             * @description Optional filesystem path for local/embedded engines
             * @example /var/lib/mydb
             */
            path?: string;
            /**
             * @description Database role for connection
             * @example readonly
             */
            role?: string;
            /**
             * @description The docker image to use
             * @example postgres:15
             */
            image?: string;
        };
        /** @description Confirmation returned after a database is successfully created or registered. Contains only the system-assigned ID. */
        DatabaseAcknowledgment: {
            /**
             * Format: int64
             * @description System-assigned unique identifier for the new database
             * @example 42
             */
            id: number;
            /** @example Database created successfully. */
            message: string;
        };
        /** @description Confirmation that a resource was deleted. */
        DeletionAcknowledgment: {
            /** @example Resource deleted successfully. */
            message: string;
        };
        /** @description Configuration for syncing data between databases with optional masking rules. */
        SyncRuleConfig: {
            /**
             * Format: int64
             * @description Source database ID registered in Mezcala
             * @example 1
             */
            from: number;
            /**
             * Format: int64
             * @description Destination database ID registered in Mezcala
             * @example 2
             */
            to: number;
            /**
             * @description Table names to exclude from the sync
             * @example [
             *       "audit_logs",
             *       "temp_data"
             *     ]
             */
            exclude?: string[];
            /**
             * @description Schemas to include in the sync
             * @default [
             *       "public"
             *     ]
             * @example [
             *       "public",
             *       "analytics"
             *     ]
             */
            schemas: string[];
            /**
             * @description Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
             * @example {
             *       "email": "MASKED",
             *       "encrypted_*": null
             *     }
             */
            data_rules?: {
                [key: string]: string;
            };
        };
        /** @description Outcome details of a sync rule execution. */
        SyncExecutionResult: {
            /**
             * Format: int64
             * @example 7
             */
            sync_id: number;
            /** @example completed */
            status: string;
            /**
             * Format: date-time
             * @example 2024-06-01T12:00:00Z
             */
            started_at?: string;
            /**
             * Format: date-time
             * @example 2024-06-01T12:00:42Z
             */
            finished_at?: string;
            /**
             * @description Number of tables processed during the sync
             * @example 14
             */
            tables_synced?: number;
            /**
             * @description Total number of rows written to the destination
             * @example 58320
             */
            rows_synced?: number;
            /** @example Sync completed successfully. */
            message?: string;
        };
    };
    responses: {
        /** @description Service is reachable and reports its current status. */
        HealthResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    status: string;
                    /** @example 1.2.3 */
                    version?: string;
                };
            };
        };
        /** @description Array of supported database engines and their available versions. */
        SupportedEnginesResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example postgres */
                    engine: string;
                    /**
                     * @example [
                     *       "14",
                     *       "15",
                     *       "16"
                     *     ]
                     */
                    versions: string[];
                }[];
            };
        };
        /** @description The database was registered or created successfully. */
        DatabaseAcknowledgmentResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DatabaseAcknowledgment"];
            };
        };
        /** @description The created or updated sync rule. */
        SyncRuleResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SyncRuleConfig"] & {
                    /**
                     * Format: int64
                     * @description System-assigned sync rule identifier
                     * @example 7
                     */
                    id: number;
                };
            };
        };
        /** @description The operation has been accepted and is running asynchronously. Poll the corresponding task status endpoint to track progress. */
        TaskAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TaskReference"];
            };
        };
        /** @description The connection URL for the specified database. */
        ConnectionUrlResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Database ID
                     * @example 42
                     */
                    id: number;
                    /**
                     * @description Fully-formed connection URL including credentials. Treat as a secret.
                     * @example postgres://admin:s3cr3t@db.example.com:5432/my-database?sslmode=require
                     */
                    connection_url: string;
                };
            };
        };
        /** @description The request is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "Field 'engine' is required."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Database with the given ID was not found."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource already exists or violates a uniqueness constraint. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CONFLICT",
                 *       "message": "A database with this name already exists."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is well-formed but contains semantic errors. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNPROCESSABLE_ENTITY",
                 *       "message": "Source and destination databases cannot be the same."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An unexpected server-side error occurred. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INTERNAL_SERVER_ERROR",
                 *       "message": "An unexpected error occurred. Please try again later."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Unique identifier of the database */
        dbID: number;
        /** @description Unique identifier of the sync rule */
        syncID: number;
        /** @description Unique identifier of the async task */
        taskID: string;
    };
    requestBodies: {
        /** @description Payload for registering or creating a database connection. */
        DatabaseRequest: {
            content: {
                "application/json": components["schemas"]["DatabaseConfig"];
            };
        };
        /** @description Payload for creating or updating a sync rule. */
        SyncRuleRequest: {
            content: {
                "application/json": components["schemas"]["SyncRuleConfig"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    checkHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HealthResponse"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSupportedEngines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SupportedEnginesResponse"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DatabaseRequest"];
        responses: {
            202: components["responses"]["TaskAccepted"];
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCreateDatabaseTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the async task */
                taskID: components["parameters"]["taskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status for a createDatabase operation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDatabaseTaskStatus"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DatabaseRequest"];
        responses: {
            201: components["responses"]["DatabaseAcknowledgmentResponse"];
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the database */
                dbID: components["parameters"]["dbID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["TaskAccepted"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getDeleteDatabaseTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the database */
                dbID: components["parameters"]["dbID"];
                /** @description Unique identifier of the async task */
                taskID: components["parameters"]["taskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status for a deleteDatabase operation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteDatabaseTaskStatus"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getDatabaseConnectionUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the database */
                dbID: components["parameters"]["dbID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ConnectionUrlResponse"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createSyncRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the database */
                dbID: components["parameters"]["dbID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SyncRuleRequest"];
        responses: {
            201: components["responses"]["SyncRuleResponse"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateSyncRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the database */
                dbID: components["parameters"]["dbID"];
                /** @description Unique identifier of the sync rule */
                syncID: components["parameters"]["syncID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SyncRuleRequest"];
        responses: {
            200: components["responses"]["SyncRuleResponse"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteSyncRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the database */
                dbID: components["parameters"]["dbID"];
                /** @description Unique identifier of the sync rule */
                syncID: components["parameters"]["syncID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync rule deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    executeSyncRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the database */
                dbID: components["parameters"]["dbID"];
            };
            cookie?: never;
        };
        /** @description Identifies which sync rule to execute. */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description ID of the sync rule to execute
                     * @example 7
                     */
                    id: number;
                };
            };
        };
        responses: {
            202: components["responses"]["TaskAccepted"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getExecuteSyncTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the database */
                dbID: components["parameters"]["dbID"];
                /** @description Unique identifier of the sync rule */
                syncID: components["parameters"]["syncID"];
                /** @description Unique identifier of the async task */
                taskID: components["parameters"]["taskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status for an executeSyncRule operation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecuteSyncTaskStatus"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
