// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateDatabaseTaskStatusStatus.
const (
	CreateDatabaseTaskStatusStatusCompleted  CreateDatabaseTaskStatusStatus = "completed"
	CreateDatabaseTaskStatusStatusFailed     CreateDatabaseTaskStatusStatus = "failed"
	CreateDatabaseTaskStatusStatusInProgress CreateDatabaseTaskStatusStatus = "in_progress"
	CreateDatabaseTaskStatusStatusPending    CreateDatabaseTaskStatusStatus = "pending"
)

// Valid indicates whether the value is a known member of the CreateDatabaseTaskStatusStatus enum.
func (e CreateDatabaseTaskStatusStatus) Valid() bool {
	switch e {
	case CreateDatabaseTaskStatusStatusCompleted:
		return true
	case CreateDatabaseTaskStatusStatusFailed:
		return true
	case CreateDatabaseTaskStatusStatusInProgress:
		return true
	case CreateDatabaseTaskStatusStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DeleteDatabaseTaskStatusStatus.
const (
	DeleteDatabaseTaskStatusStatusCompleted  DeleteDatabaseTaskStatusStatus = "completed"
	DeleteDatabaseTaskStatusStatusFailed     DeleteDatabaseTaskStatusStatus = "failed"
	DeleteDatabaseTaskStatusStatusInProgress DeleteDatabaseTaskStatusStatus = "in_progress"
	DeleteDatabaseTaskStatusStatusPending    DeleteDatabaseTaskStatusStatus = "pending"
)

// Valid indicates whether the value is a known member of the DeleteDatabaseTaskStatusStatus enum.
func (e DeleteDatabaseTaskStatusStatus) Valid() bool {
	switch e {
	case DeleteDatabaseTaskStatusStatusCompleted:
		return true
	case DeleteDatabaseTaskStatusStatusFailed:
		return true
	case DeleteDatabaseTaskStatusStatusInProgress:
		return true
	case DeleteDatabaseTaskStatusStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ExecuteSyncTaskStatusStatus.
const (
	ExecuteSyncTaskStatusStatusCompleted  ExecuteSyncTaskStatusStatus = "completed"
	ExecuteSyncTaskStatusStatusFailed     ExecuteSyncTaskStatusStatus = "failed"
	ExecuteSyncTaskStatusStatusInProgress ExecuteSyncTaskStatusStatus = "in_progress"
	ExecuteSyncTaskStatusStatusPending    ExecuteSyncTaskStatusStatus = "pending"
)

// Valid indicates whether the value is a known member of the ExecuteSyncTaskStatusStatus enum.
func (e ExecuteSyncTaskStatusStatus) Valid() bool {
	switch e {
	case ExecuteSyncTaskStatusStatusCompleted:
		return true
	case ExecuteSyncTaskStatusStatusFailed:
		return true
	case ExecuteSyncTaskStatusStatusInProgress:
		return true
	case ExecuteSyncTaskStatusStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatusBaseStatus.
const (
	TaskStatusBaseStatusCompleted  TaskStatusBaseStatus = "completed"
	TaskStatusBaseStatusFailed     TaskStatusBaseStatus = "failed"
	TaskStatusBaseStatusInProgress TaskStatusBaseStatus = "in_progress"
	TaskStatusBaseStatusPending    TaskStatusBaseStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskStatusBaseStatus enum.
func (e TaskStatusBaseStatus) Valid() bool {
	switch e {
	case TaskStatusBaseStatusCompleted:
		return true
	case TaskStatusBaseStatusFailed:
		return true
	case TaskStatusBaseStatusInProgress:
		return true
	case TaskStatusBaseStatusPending:
		return true
	default:
		return false
	}
}

// CreateDatabaseTaskStatus defines model for CreateDatabaseTaskStatus.
type CreateDatabaseTaskStatus struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Error Standard error envelope returned for all 4xx and 5xx responses.
	Error *Error `json:"error,omitempty"`

	// Message Human-readable status message
	Message *string `json:"message,omitempty"`

	// Result Confirmation returned after a database is successfully created or registered. Contains only the system-assigned ID.
	Result *DatabaseAcknowledgment        `json:"result,omitempty"`
	Status CreateDatabaseTaskStatusStatus `json:"status"`
	TaskId openapi_types.UUID             `json:"task_id"`
}

// CreateDatabaseTaskStatusStatus defines model for CreateDatabaseTaskStatus.Status.
type CreateDatabaseTaskStatusStatus string

// DatabaseAcknowledgment Confirmation returned after a database is successfully created or registered. Contains only the system-assigned ID.
type DatabaseAcknowledgment struct {
	// Id System-assigned unique identifier for the new database
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

// DatabaseConfig Connection configuration for a database.
type DatabaseConfig struct {
	// Alias Optional human-friendly label
	Alias  *string `json:"alias,omitempty"`
	Engine string  `json:"engine"`
	Host   string  `json:"host"`

	// Image The docker image to use
	Image    *string `json:"image,omitempty"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`

	// Path Optional filesystem path for local/embedded engines
	Path *string `json:"path,omitempty"`
	Port string  `json:"port"`

	// Role Database role for connection
	Role     *string `json:"role,omitempty"`
	SslMode  *string `json:"ssl_mode,omitempty"`
	Username string  `json:"username"`
	Version  *string `json:"version,omitempty"`
}

// DeleteDatabaseTaskStatus defines model for DeleteDatabaseTaskStatus.
type DeleteDatabaseTaskStatus struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Error Standard error envelope returned for all 4xx and 5xx responses.
	Error *Error `json:"error,omitempty"`

	// Message Human-readable status message
	Message *string `json:"message,omitempty"`

	// Result Confirmation that a resource was deleted.
	Result *DeletionAcknowledgment        `json:"result,omitempty"`
	Status DeleteDatabaseTaskStatusStatus `json:"status"`
	TaskId openapi_types.UUID             `json:"task_id"`
}

// DeleteDatabaseTaskStatusStatus defines model for DeleteDatabaseTaskStatus.Status.
type DeleteDatabaseTaskStatusStatus string

// DeletionAcknowledgment Confirmation that a resource was deleted.
type DeletionAcknowledgment struct {
	Message string `json:"message"`
}

// Error Standard error envelope returned for all 4xx and 5xx responses.
type Error struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Details Optional additional context about the error
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable description of the error
	Message string `json:"message"`
}

// ExecuteSyncTaskStatus defines model for ExecuteSyncTaskStatus.
type ExecuteSyncTaskStatus struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Error Standard error envelope returned for all 4xx and 5xx responses.
	Error *Error `json:"error,omitempty"`

	// Message Human-readable status message
	Message *string `json:"message,omitempty"`

	// Result Outcome details of a sync rule execution.
	Result *SyncExecutionResult        `json:"result,omitempty"`
	Status ExecuteSyncTaskStatusStatus `json:"status"`
	TaskId openapi_types.UUID          `json:"task_id"`
}

// ExecuteSyncTaskStatusStatus defines model for ExecuteSyncTaskStatus.Status.
type ExecuteSyncTaskStatusStatus string

// SyncExecutionResult Outcome details of a sync rule execution.
type SyncExecutionResult struct {
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Message    *string    `json:"message,omitempty"`

	// RowsSynced Total number of rows written to the destination
	RowsSynced *int       `json:"rows_synced,omitempty"`
	StartedAt  *time.Time `json:"started_at,omitempty"`
	Status     string     `json:"status"`
	SyncId     int64      `json:"sync_id"`

	// TablesSynced Number of tables processed during the sync
	TablesSynced *int `json:"tables_synced,omitempty"`
}

// SyncRuleConfig Configuration for syncing data between databases with optional masking rules.
type SyncRuleConfig struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

// TaskReference Returned immediately when an async operation is accepted.
type TaskReference struct {
	// TaskId Unique identifier for the async task
	TaskId openapi_types.UUID `json:"task_id"`
}

// TaskStatusBase Common fields shared by all task status responses. When `status` is `completed` the operation-specific `result` field is populated. When `status` is `failed` the `error` field is populated.
type TaskStatusBase struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Error Standard error envelope returned for all 4xx and 5xx responses.
	Error *Error `json:"error,omitempty"`

	// Message Human-readable status message
	Message *string              `json:"message,omitempty"`
	Status  TaskStatusBaseStatus `json:"status"`
	TaskId  openapi_types.UUID   `json:"task_id"`
}

// TaskStatusBaseStatus defines model for TaskStatusBase.Status.
type TaskStatusBaseStatus string

// DbID defines model for dbID.
type DbID = int64

// SyncID defines model for syncID.
type SyncID = int64

// TaskID defines model for taskID.
type TaskID = openapi_types.UUID

// BadRequest Standard error envelope returned for all 4xx and 5xx responses.
type BadRequest = Error

// Conflict Standard error envelope returned for all 4xx and 5xx responses.
type Conflict = Error

// ConnectionUrlResponse defines model for ConnectionUrlResponse.
type ConnectionUrlResponse struct {
	// ConnectionUrl Fully-formed connection URL including credentials. Treat as a secret.
	ConnectionUrl string `json:"connection_url"`

	// Id Database ID
	Id int64 `json:"id"`
}

// DatabaseAcknowledgmentResponse Confirmation returned after a database is successfully created or registered. Contains only the system-assigned ID.
type DatabaseAcknowledgmentResponse = DatabaseAcknowledgment

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string  `json:"status"`
	Version *string `json:"version,omitempty"`
}

// InternalServerError Standard error envelope returned for all 4xx and 5xx responses.
type InternalServerError = Error

// NotFound Standard error envelope returned for all 4xx and 5xx responses.
type NotFound = Error

// SupportedEnginesResponse defines model for SupportedEnginesResponse.
type SupportedEnginesResponse = []struct {
	Engine   string   `json:"engine"`
	Versions []string `json:"versions"`
}

// SyncRuleResponse defines model for SyncRuleResponse.
type SyncRuleResponse struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Id System-assigned sync rule identifier
	Id int64 `json:"id"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

// TaskAccepted Returned immediately when an async operation is accepted.
type TaskAccepted = TaskReference

// UnprocessableEntity Standard error envelope returned for all 4xx and 5xx responses.
type UnprocessableEntity = Error

// DatabaseRequest Connection configuration for a database.
type DatabaseRequest = DatabaseConfig

// SyncRuleRequest Configuration for syncing data between databases with optional masking rules.
type SyncRuleRequest = SyncRuleConfig

// ExecuteSyncRuleJSONBody defines parameters for ExecuteSyncRule.
type ExecuteSyncRuleJSONBody struct {
	// Id ID of the sync rule to execute
	Id int64 `json:"id"`
}

// AddDatabaseJSONRequestBody defines body for AddDatabase for application/json ContentType.
type AddDatabaseJSONRequestBody = DatabaseConfig

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = DatabaseConfig

// ExecuteSyncRuleJSONRequestBody defines body for ExecuteSyncRule for application/json ContentType.
type ExecuteSyncRuleJSONRequestBody ExecuteSyncRuleJSONBody

// CreateSyncRuleJSONRequestBody defines body for CreateSyncRule for application/json ContentType.
type CreateSyncRuleJSONRequestBody = SyncRuleConfig

// UpdateSyncRuleJSONRequestBody defines body for UpdateSyncRule for application/json ContentType.
type UpdateSyncRuleJSONRequestBody = SyncRuleConfig

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register an existing external database
	// (POST /databases/add)
	AddDatabase(w http.ResponseWriter, r *http.Request)
	// Create a new managed database
	// (POST /databases/create)
	CreateDatabase(w http.ResponseWriter, r *http.Request)
	// Get the status of a createDatabase task
	// (GET /databases/create/tasks/{taskID})
	GetCreateDatabaseTaskStatus(w http.ResponseWriter, r *http.Request, taskID TaskID)
	// List all supported database engines and versions
	// (GET /databases/supported)
	GetSupportedEngines(w http.ResponseWriter, r *http.Request)
	// Get the connection URL for a database
	// (GET /databases/{dbID}/connection-url)
	GetDatabaseConnectionUrl(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Delete a database by ID
	// (DELETE /databases/{dbID}/delete)
	DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Get the status of a deleteDatabase task
	// (GET /databases/{dbID}/delete/tasks/{taskID})
	GetDeleteDatabaseTaskStatus(w http.ResponseWriter, r *http.Request, dbid DbID, taskID TaskID)
	// Trigger execution of a sync rule
	// (PUT /databases/{dbID}/sync)
	ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Create a new sync rule for a database
	// (POST /databases/{dbID}/sync/init)
	CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Delete a sync rule
	// (DELETE /databases/{dbID}/sync/{syncID}/delete)
	DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID)
	// Get the status of an executeSyncRule task
	// (GET /databases/{dbID}/sync/{syncID}/tasks/{taskID})
	GetExecuteSyncTaskStatus(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID, taskID TaskID)
	// Update an existing sync rule
	// (PUT /databases/{dbID}/sync/{syncID}/update)
	UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID)
	// Check Mezcala health
	// (GET /health)
	CheckHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register an existing external database
// (POST /databases/add)
func (_ Unimplemented) AddDatabase(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new managed database
// (POST /databases/create)
func (_ Unimplemented) CreateDatabase(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the status of a createDatabase task
// (GET /databases/create/tasks/{taskID})
func (_ Unimplemented) GetCreateDatabaseTaskStatus(w http.ResponseWriter, r *http.Request, taskID TaskID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all supported database engines and versions
// (GET /databases/supported)
func (_ Unimplemented) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the connection URL for a database
// (GET /databases/{dbID}/connection-url)
func (_ Unimplemented) GetDatabaseConnectionUrl(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a database by ID
// (DELETE /databases/{dbID}/delete)
func (_ Unimplemented) DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the status of a deleteDatabase task
// (GET /databases/{dbID}/delete/tasks/{taskID})
func (_ Unimplemented) GetDeleteDatabaseTaskStatus(w http.ResponseWriter, r *http.Request, dbid DbID, taskID TaskID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger execution of a sync rule
// (PUT /databases/{dbID}/sync)
func (_ Unimplemented) ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new sync rule for a database
// (POST /databases/{dbID}/sync/init)
func (_ Unimplemented) CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a sync rule
// (DELETE /databases/{dbID}/sync/{syncID}/delete)
func (_ Unimplemented) DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the status of an executeSyncRule task
// (GET /databases/{dbID}/sync/{syncID}/tasks/{taskID})
func (_ Unimplemented) GetExecuteSyncTaskStatus(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID, taskID TaskID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing sync rule
// (PUT /databases/{dbID}/sync/{syncID}/update)
func (_ Unimplemented) UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check Mezcala health
// (GET /health)
func (_ Unimplemented) CheckHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AddDatabase operation middleware
func (siw *ServerInterfaceWrapper) AddDatabase(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddDatabase(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDatabase operation middleware
func (siw *ServerInterfaceWrapper) CreateDatabase(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDatabase(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCreateDatabaseTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCreateDatabaseTaskStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskID" -------------
	var taskID TaskID

	err = runtime.BindStyledParameterWithOptions("simple", "taskID", chi.URLParam(r, "taskID"), &taskID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCreateDatabaseTaskStatus(w, r, taskID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupportedEngines operation middleware
func (siw *ServerInterfaceWrapper) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupportedEngines(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDatabaseConnectionUrl operation middleware
func (siw *ServerInterfaceWrapper) GetDatabaseConnectionUrl(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDatabaseConnectionUrl(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDatabase operation middleware
func (siw *ServerInterfaceWrapper) DeleteDatabase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDatabase(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeleteDatabaseTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) GetDeleteDatabaseTaskStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	// ------------- Path parameter "taskID" -------------
	var taskID TaskID

	err = runtime.BindStyledParameterWithOptions("simple", "taskID", chi.URLParam(r, "taskID"), &taskID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeleteDatabaseTaskStatus(w, r, dbid, taskID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteSyncRule operation middleware
func (siw *ServerInterfaceWrapper) ExecuteSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteSyncRule(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSyncRule operation middleware
func (siw *ServerInterfaceWrapper) CreateSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSyncRule(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSyncRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	// ------------- Path parameter "syncID" -------------
	var syncID SyncID

	err = runtime.BindStyledParameterWithOptions("simple", "syncID", chi.URLParam(r, "syncID"), &syncID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "syncID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSyncRule(w, r, dbid, syncID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecuteSyncTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) GetExecuteSyncTaskStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	// ------------- Path parameter "syncID" -------------
	var syncID SyncID

	err = runtime.BindStyledParameterWithOptions("simple", "syncID", chi.URLParam(r, "syncID"), &syncID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "syncID", Err: err})
		return
	}

	// ------------- Path parameter "taskID" -------------
	var taskID TaskID

	err = runtime.BindStyledParameterWithOptions("simple", "taskID", chi.URLParam(r, "taskID"), &taskID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecuteSyncTaskStatus(w, r, dbid, syncID, taskID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSyncRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	// ------------- Path parameter "syncID" -------------
	var syncID SyncID

	err = runtime.BindStyledParameterWithOptions("simple", "syncID", chi.URLParam(r, "syncID"), &syncID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "syncID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSyncRule(w, r, dbid, syncID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckHealth operation middleware
func (siw *ServerInterfaceWrapper) CheckHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckHealth(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/add", wrapper.AddDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/create", wrapper.CreateDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/databases/create/tasks/{taskID}", wrapper.GetCreateDatabaseTaskStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/databases/supported", wrapper.GetSupportedEngines)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/databases/{dbID}/connection-url", wrapper.GetDatabaseConnectionUrl)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/databases/{dbID}/delete", wrapper.DeleteDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/databases/{dbID}/delete/tasks/{taskID}", wrapper.GetDeleteDatabaseTaskStatus)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/databases/{dbID}/sync", wrapper.ExecuteSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/{dbID}/sync/init", wrapper.CreateSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/databases/{dbID}/sync/{syncID}/delete", wrapper.DeleteSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/databases/{dbID}/sync/{syncID}/tasks/{taskID}", wrapper.GetExecuteSyncTaskStatus)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/databases/{dbID}/sync/{syncID}/update", wrapper.UpdateSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.CheckHealth)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ConnectionUrlResponseJSONResponse struct {
	// ConnectionUrl Fully-formed connection URL including credentials. Treat as a secret.
	ConnectionUrl string `json:"connection_url"`

	// Id Database ID
	Id int64 `json:"id"`
}

type DatabaseAcknowledgmentResponseJSONResponse DatabaseAcknowledgment

type HealthResponseJSONResponse struct {
	Status  string  `json:"status"`
	Version *string `json:"version,omitempty"`
}

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type SupportedEnginesResponseJSONResponse []struct {
	Engine   string   `json:"engine"`
	Versions []string `json:"versions"`
}

type SyncRuleResponseJSONResponse struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Id System-assigned sync rule identifier
	Id int64 `json:"id"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

type TaskAcceptedJSONResponse TaskReference

type UnprocessableEntityJSONResponse Error

type AddDatabaseRequestObject struct {
	Body *AddDatabaseJSONRequestBody
}

type AddDatabaseResponseObject interface {
	VisitAddDatabaseResponse(w http.ResponseWriter) error
}

type AddDatabase201JSONResponse struct {
	DatabaseAcknowledgmentResponseJSONResponse
}

func (response AddDatabase201JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase400JSONResponse struct{ BadRequestJSONResponse }

func (response AddDatabase400JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase409JSONResponse struct{ ConflictJSONResponse }

func (response AddDatabase409JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AddDatabase500JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabaseRequestObject struct {
	Body *CreateDatabaseJSONRequestBody
}

type CreateDatabaseResponseObject interface {
	VisitCreateDatabaseResponse(w http.ResponseWriter) error
}

type CreateDatabase202JSONResponse struct{ TaskAcceptedJSONResponse }

func (response CreateDatabase202JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateDatabase400JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase409JSONResponse struct{ ConflictJSONResponse }

func (response CreateDatabase409JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateDatabase500JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCreateDatabaseTaskStatusRequestObject struct {
	TaskID TaskID `json:"taskID"`
}

type GetCreateDatabaseTaskStatusResponseObject interface {
	VisitGetCreateDatabaseTaskStatusResponse(w http.ResponseWriter) error
}

type GetCreateDatabaseTaskStatus200JSONResponse CreateDatabaseTaskStatus

func (response GetCreateDatabaseTaskStatus200JSONResponse) VisitGetCreateDatabaseTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCreateDatabaseTaskStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCreateDatabaseTaskStatus404JSONResponse) VisitGetCreateDatabaseTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCreateDatabaseTaskStatus500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetCreateDatabaseTaskStatus500JSONResponse) VisitGetCreateDatabaseTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSupportedEnginesRequestObject struct {
}

type GetSupportedEnginesResponseObject interface {
	VisitGetSupportedEnginesResponse(w http.ResponseWriter) error
}

type GetSupportedEngines200JSONResponse struct {
	SupportedEnginesResponseJSONResponse
}

func (response GetSupportedEngines200JSONResponse) VisitGetSupportedEnginesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSupportedEngines500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetSupportedEngines500JSONResponse) VisitGetSupportedEnginesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDatabaseConnectionUrlRequestObject struct {
	DbID DbID `json:"dbID"`
}

type GetDatabaseConnectionUrlResponseObject interface {
	VisitGetDatabaseConnectionUrlResponse(w http.ResponseWriter) error
}

type GetDatabaseConnectionUrl200JSONResponse struct {
	ConnectionUrlResponseJSONResponse
}

func (response GetDatabaseConnectionUrl200JSONResponse) VisitGetDatabaseConnectionUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDatabaseConnectionUrl404JSONResponse struct{ NotFoundJSONResponse }

func (response GetDatabaseConnectionUrl404JSONResponse) VisitGetDatabaseConnectionUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDatabaseConnectionUrl500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetDatabaseConnectionUrl500JSONResponse) VisitGetDatabaseConnectionUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDatabaseRequestObject struct {
	DbID DbID `json:"dbID"`
}

type DeleteDatabaseResponseObject interface {
	VisitDeleteDatabaseResponse(w http.ResponseWriter) error
}

type DeleteDatabase202JSONResponse struct{ TaskAcceptedJSONResponse }

func (response DeleteDatabase202JSONResponse) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDatabase404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteDatabase404JSONResponse) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteDatabase500JSONResponse) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeleteDatabaseTaskStatusRequestObject struct {
	DbID   DbID   `json:"dbID"`
	TaskID TaskID `json:"taskID"`
}

type GetDeleteDatabaseTaskStatusResponseObject interface {
	VisitGetDeleteDatabaseTaskStatusResponse(w http.ResponseWriter) error
}

type GetDeleteDatabaseTaskStatus200JSONResponse DeleteDatabaseTaskStatus

func (response GetDeleteDatabaseTaskStatus200JSONResponse) VisitGetDeleteDatabaseTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeleteDatabaseTaskStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response GetDeleteDatabaseTaskStatus404JSONResponse) VisitGetDeleteDatabaseTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeleteDatabaseTaskStatus500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetDeleteDatabaseTaskStatus500JSONResponse) VisitGetDeleteDatabaseTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRuleRequestObject struct {
	DbID DbID `json:"dbID"`
	Body *ExecuteSyncRuleJSONRequestBody
}

type ExecuteSyncRuleResponseObject interface {
	VisitExecuteSyncRuleResponse(w http.ResponseWriter) error
}

type ExecuteSyncRule202JSONResponse struct{ TaskAcceptedJSONResponse }

func (response ExecuteSyncRule202JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response ExecuteSyncRule400JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response ExecuteSyncRule404JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ExecuteSyncRule422JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ExecuteSyncRule500JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRuleRequestObject struct {
	DbID DbID `json:"dbID"`
	Body *CreateSyncRuleJSONRequestBody
}

type CreateSyncRuleResponseObject interface {
	VisitCreateSyncRuleResponse(w http.ResponseWriter) error
}

type CreateSyncRule201JSONResponse struct{ SyncRuleResponseJSONResponse }

func (response CreateSyncRule201JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSyncRule400JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateSyncRule404JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateSyncRule500JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSyncRuleRequestObject struct {
	DbID   DbID   `json:"dbID"`
	SyncID SyncID `json:"syncID"`
}

type DeleteSyncRuleResponseObject interface {
	VisitDeleteSyncRuleResponse(w http.ResponseWriter) error
}

type DeleteSyncRule204Response struct {
}

func (response DeleteSyncRule204Response) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSyncRule404JSONResponse) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteSyncRule500JSONResponse) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetExecuteSyncTaskStatusRequestObject struct {
	DbID   DbID   `json:"dbID"`
	SyncID SyncID `json:"syncID"`
	TaskID TaskID `json:"taskID"`
}

type GetExecuteSyncTaskStatusResponseObject interface {
	VisitGetExecuteSyncTaskStatusResponse(w http.ResponseWriter) error
}

type GetExecuteSyncTaskStatus200JSONResponse ExecuteSyncTaskStatus

func (response GetExecuteSyncTaskStatus200JSONResponse) VisitGetExecuteSyncTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExecuteSyncTaskStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response GetExecuteSyncTaskStatus404JSONResponse) VisitGetExecuteSyncTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetExecuteSyncTaskStatus500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetExecuteSyncTaskStatus500JSONResponse) VisitGetExecuteSyncTaskStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRuleRequestObject struct {
	DbID   DbID   `json:"dbID"`
	SyncID SyncID `json:"syncID"`
	Body   *UpdateSyncRuleJSONRequestBody
}

type UpdateSyncRuleResponseObject interface {
	VisitUpdateSyncRuleResponse(w http.ResponseWriter) error
}

type UpdateSyncRule200JSONResponse struct{ SyncRuleResponseJSONResponse }

func (response UpdateSyncRule200JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSyncRule400JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateSyncRule404JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateSyncRule500JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealthRequestObject struct {
}

type CheckHealthResponseObject interface {
	VisitCheckHealthResponse(w http.ResponseWriter) error
}

type CheckHealth200JSONResponse struct{ HealthResponseJSONResponse }

func (response CheckHealth200JSONResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealth500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CheckHealth500JSONResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register an existing external database
	// (POST /databases/add)
	AddDatabase(ctx context.Context, request AddDatabaseRequestObject) (AddDatabaseResponseObject, error)
	// Create a new managed database
	// (POST /databases/create)
	CreateDatabase(ctx context.Context, request CreateDatabaseRequestObject) (CreateDatabaseResponseObject, error)
	// Get the status of a createDatabase task
	// (GET /databases/create/tasks/{taskID})
	GetCreateDatabaseTaskStatus(ctx context.Context, request GetCreateDatabaseTaskStatusRequestObject) (GetCreateDatabaseTaskStatusResponseObject, error)
	// List all supported database engines and versions
	// (GET /databases/supported)
	GetSupportedEngines(ctx context.Context, request GetSupportedEnginesRequestObject) (GetSupportedEnginesResponseObject, error)
	// Get the connection URL for a database
	// (GET /databases/{dbID}/connection-url)
	GetDatabaseConnectionUrl(ctx context.Context, request GetDatabaseConnectionUrlRequestObject) (GetDatabaseConnectionUrlResponseObject, error)
	// Delete a database by ID
	// (DELETE /databases/{dbID}/delete)
	DeleteDatabase(ctx context.Context, request DeleteDatabaseRequestObject) (DeleteDatabaseResponseObject, error)
	// Get the status of a deleteDatabase task
	// (GET /databases/{dbID}/delete/tasks/{taskID})
	GetDeleteDatabaseTaskStatus(ctx context.Context, request GetDeleteDatabaseTaskStatusRequestObject) (GetDeleteDatabaseTaskStatusResponseObject, error)
	// Trigger execution of a sync rule
	// (PUT /databases/{dbID}/sync)
	ExecuteSyncRule(ctx context.Context, request ExecuteSyncRuleRequestObject) (ExecuteSyncRuleResponseObject, error)
	// Create a new sync rule for a database
	// (POST /databases/{dbID}/sync/init)
	CreateSyncRule(ctx context.Context, request CreateSyncRuleRequestObject) (CreateSyncRuleResponseObject, error)
	// Delete a sync rule
	// (DELETE /databases/{dbID}/sync/{syncID}/delete)
	DeleteSyncRule(ctx context.Context, request DeleteSyncRuleRequestObject) (DeleteSyncRuleResponseObject, error)
	// Get the status of an executeSyncRule task
	// (GET /databases/{dbID}/sync/{syncID}/tasks/{taskID})
	GetExecuteSyncTaskStatus(ctx context.Context, request GetExecuteSyncTaskStatusRequestObject) (GetExecuteSyncTaskStatusResponseObject, error)
	// Update an existing sync rule
	// (PUT /databases/{dbID}/sync/{syncID}/update)
	UpdateSyncRule(ctx context.Context, request UpdateSyncRuleRequestObject) (UpdateSyncRuleResponseObject, error)
	// Check Mezcala health
	// (GET /health)
	CheckHealth(ctx context.Context, request CheckHealthRequestObject) (CheckHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AddDatabase operation middleware
func (sh *strictHandler) AddDatabase(w http.ResponseWriter, r *http.Request) {
	var request AddDatabaseRequestObject

	var body AddDatabaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddDatabase(ctx, request.(AddDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddDatabaseResponseObject); ok {
		if err := validResponse.VisitAddDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDatabase operation middleware
func (sh *strictHandler) CreateDatabase(w http.ResponseWriter, r *http.Request) {
	var request CreateDatabaseRequestObject

	var body CreateDatabaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDatabase(ctx, request.(CreateDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDatabaseResponseObject); ok {
		if err := validResponse.VisitCreateDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCreateDatabaseTaskStatus operation middleware
func (sh *strictHandler) GetCreateDatabaseTaskStatus(w http.ResponseWriter, r *http.Request, taskID TaskID) {
	var request GetCreateDatabaseTaskStatusRequestObject

	request.TaskID = taskID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCreateDatabaseTaskStatus(ctx, request.(GetCreateDatabaseTaskStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCreateDatabaseTaskStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCreateDatabaseTaskStatusResponseObject); ok {
		if err := validResponse.VisitGetCreateDatabaseTaskStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSupportedEngines operation middleware
func (sh *strictHandler) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {
	var request GetSupportedEnginesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSupportedEngines(ctx, request.(GetSupportedEnginesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSupportedEngines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSupportedEnginesResponseObject); ok {
		if err := validResponse.VisitGetSupportedEnginesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDatabaseConnectionUrl operation middleware
func (sh *strictHandler) GetDatabaseConnectionUrl(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request GetDatabaseConnectionUrlRequestObject

	request.DbID = dbid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDatabaseConnectionUrl(ctx, request.(GetDatabaseConnectionUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDatabaseConnectionUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDatabaseConnectionUrlResponseObject); ok {
		if err := validResponse.VisitGetDatabaseConnectionUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDatabase operation middleware
func (sh *strictHandler) DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request DeleteDatabaseRequestObject

	request.DbID = dbid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDatabase(ctx, request.(DeleteDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDatabaseResponseObject); ok {
		if err := validResponse.VisitDeleteDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeleteDatabaseTaskStatus operation middleware
func (sh *strictHandler) GetDeleteDatabaseTaskStatus(w http.ResponseWriter, r *http.Request, dbid DbID, taskID TaskID) {
	var request GetDeleteDatabaseTaskStatusRequestObject

	request.DbID = dbid
	request.TaskID = taskID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeleteDatabaseTaskStatus(ctx, request.(GetDeleteDatabaseTaskStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeleteDatabaseTaskStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeleteDatabaseTaskStatusResponseObject); ok {
		if err := validResponse.VisitGetDeleteDatabaseTaskStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExecuteSyncRule operation middleware
func (sh *strictHandler) ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request ExecuteSyncRuleRequestObject

	request.DbID = dbid

	var body ExecuteSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExecuteSyncRule(ctx, request.(ExecuteSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExecuteSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExecuteSyncRuleResponseObject); ok {
		if err := validResponse.VisitExecuteSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSyncRule operation middleware
func (sh *strictHandler) CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request CreateSyncRuleRequestObject

	request.DbID = dbid

	var body CreateSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSyncRule(ctx, request.(CreateSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSyncRuleResponseObject); ok {
		if err := validResponse.VisitCreateSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSyncRule operation middleware
func (sh *strictHandler) DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	var request DeleteSyncRuleRequestObject

	request.DbID = dbid
	request.SyncID = syncID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSyncRule(ctx, request.(DeleteSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSyncRuleResponseObject); ok {
		if err := validResponse.VisitDeleteSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExecuteSyncTaskStatus operation middleware
func (sh *strictHandler) GetExecuteSyncTaskStatus(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID, taskID TaskID) {
	var request GetExecuteSyncTaskStatusRequestObject

	request.DbID = dbid
	request.SyncID = syncID
	request.TaskID = taskID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExecuteSyncTaskStatus(ctx, request.(GetExecuteSyncTaskStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExecuteSyncTaskStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExecuteSyncTaskStatusResponseObject); ok {
		if err := validResponse.VisitGetExecuteSyncTaskStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSyncRule operation middleware
func (sh *strictHandler) UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	var request UpdateSyncRuleRequestObject

	request.DbID = dbid
	request.SyncID = syncID

	var body UpdateSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSyncRule(ctx, request.(UpdateSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSyncRuleResponseObject); ok {
		if err := validResponse.VisitUpdateSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckHealth operation middleware
func (sh *strictHandler) CheckHealth(w http.ResponseWriter, r *http.Request) {
	var request CheckHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckHealth(ctx, request.(CheckHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckHealthResponseObject); ok {
		if err := validResponse.VisitCheckHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xc/W4jOXJ/FaIT4JJAH7bH9twZCBLPWLNr3Jztk+0EyWRgUc2SxDOb3UeybWsNAXmI",
	"PGGeJCiyv5ttfYxmd3L/7MoSmyxW/eq7el6DMI6SWII0Ojh7DRKqaAQGlP2LTS8v7P9Bh4onhscyOAvu",
	"Jf9rCoQzkIbPOCgSz4hZAGHU0CnVEPQCjgsTahZBL5A0guDMbdYLFPw15QpYcGZUCr1AhwuIKJ4CLzRK",
	"BARnx0e9YBariJrgLODSnB4HvcAsE3B/whxUsFr1Ar2U4VYE4gNEpaKDwmy/jWh8vxmJhurHrUiklkZ8",
	"zE9jtuFGNAbvZvT3J7PT4/7J+8P3/eOT06P+9N0s7B+Ffzh9Nzs9pTN6GlQukqaclffQRnE5D1Z4DzwN",
	"tPkQMw4WGheZrMfuB/wqjKUBaT/SJBE8pHjZ4V803vi1QuDfK5gFZ8HfDUvsDd2vepjv+zGWM54dXmfd",
	"DV2KmDIyixVRMOfaANJJYkVCBdTgZ1pgkYSxlBDis4MW11a94HYpw3Eq9n6PfN/N7lEQHiuSJiy/RIFX",
	"D+lWKDqJpXYC+UDZ5ncoIIIrGQr7w/nFw3j05/vR7V3QCyLQms7x+08cBCO/AznnEn5HuCY5HYNg1duQ",
	"GSOlYuXjwd0CSAYt3DqiArEIDPkwo1xo8kQFZ9SJb9ULkJ2Ch7vd8eP11afPlx/rFzwvofLMzYKYBdcE",
	"lY1QoYCyJYEXro3e33V1nKqwuT3e+InHghrQhJLU2gcJWiOAtVGUS5NzIMPzvRLjDAFbwTZRcQLKZIpc",
	"6sdDqkTbUn1KhVj2M7GUi8n9+DPhMhQpQ6yGCqwpo0IPyB2imVC8h4ZQgRn8lwx6FbuUxNrMFeiz4ZCy",
	"iMsz/S5U78y/sukgWzQI4+js5Pjd0TBa9nMB/YvWIooZ/HMGwbap6gWcta+Q2xRiDefWbqZUvC+BtY8N",
	"ln0tnoqnf4HQdEm+wTzUe+uUEgjRBbACiFbOOdHn4aOMnwWweQTS7CTwText/ZiuK5SqQnVhfJ26WhMG",
	"jOg0DEHrGcLGXuRnoMIs9oBUbahJ7aeW1J9Aad5Q++BwcDR453FndYlmu24ixFtQTzwEZwRpuKBTAYRK",
	"RhQksTKacKNJmCoF0hC3r+XApTSgJBX4PChnHXaxX5dXd6Px1fnnh9vR+N9G44fReHw9rhszSVIJLwmE",
	"KArAk0gcWpLYgNwIQNkZtSR0TrkkaG3UPgxb/Vxt79nXnEGTBjzrKjaf4lSynXhwdX338On6/uqidu+L",
	"hgkHMudPIMnlhUWqjA2Z4ZF79lnASnPOYnAHWXtuD7pNE8QFsJH1nnonHeAGIt1WBueQ64DPzarPLmYa",
	"omtPfAkO0eYdnuB/TlEHitNaG2RfUKXosqVEGTWVY9r61NqijSL8AQNhnTOuNDjuBG3VzSyAK0KfKBdW",
	"BfNDHdOLgG4HZlMhrmfB2ZftYrteUzg+J3S71AaiPtWazyUqSR7bVZKAqnd6v5NzarP9a5c3yux1HnFW",
	"SbKMvKP68TwMITHA9uZucNMxzECBDKFLu5CVdnOyoJpMASShGSFW/mh/UyltjIw0L1Qs41SL5YDcxEJY",
	"/Q9j5cJjG55g1pRZZAKSJTGXhpiYGEXDR5KoGNVGY5iy6gX3MlEx+jAE10gabpY7mar7q5vx9cfR7e35",
	"h8+jh9HV3eXdf9Ss1m0WCEpGGGjDpbt0jnlNQirRokzBBQo0gu8QdD+DEHl8N00NhimGcqmJhohKw0Nn",
	"w1G7irMtyj9aBOWmFyV7W3jozRSpfOYD1eBRJAU6FWbnGKatDC1eVICBARklk7B2rUmJxgG5lgSPF4B/",
	"9sjEkTcpWYZikvBcmq3LiwxUHTS2zIS1Kaj2iAQFJlVoLOjMgKpmtVzXAq2qNpdh2YB8zAmLpVhmJZC6",
	"GXIE9nYwYGmrhJFHtFUObB1wVxSk6tsKD++PM9dFeTZuzzf2+aZG3cEnlzx4D+2SNDNRDjVl6N5kJRXc",
	"qUt9v2v7gQqySCMq+zPFQTKxJIJOQdSTJRWzPpv6nPq2QcAidtWBcnU94/ImVFEmC082EIePoIhdgdY0",
	"rYu7TPNsgNHa2VW0qtRUcj3fAwnV+jlWrP6Qyx2rZaxinXcPs3hDGjMuwKkIwZVWuiIOqRhCNAXGMKp2",
	"kUjtpsMnqoaCT4fR0i8pDGfqZGNy61upYgFvpLD4sysZFYCsUaKAMlR239Zai4fI+qbX2hOdyXSqMW9p",
	"Ssmm7G/EmI0s7GStchbRo8VnxqzK6RXJe1UXBPwYfgicZ9iPH2K1a23nhyhhGS3OWmUOJfdFfjrf9kVm",
	"QQ2hZb6DeZUjkbWNnteEj4tUyT22pQl/y3oXOXXDZRkqGVV5JgzyCUScQOlXLauFIMcvLzYMO3l5IUVV",
	"tX2tMFOe+il/ouGCS+ij6tl8xJ1mF1dVs5q6tnSHgaFcOMwyxp05uqmc7qr8HWarfMRiAF4ModM4NdYd",
	"W3ICD9cqUqrv+7P1ScV9Kj/mbYp8z/J2HWlxI/1eJ+SMaW/K+gXC1AAmYb+hruPxjhIey7F7ZCdFl2QC",
	"5Y0wrdxO1V2/iEc2G5KMxKkJ4wiFZgGVqbyP3LYXrD+Ksq70IAjkz7cVY8Yl1wtgD7Th5Y4Ojo77B6f9",
	"g8O7w6Ozg4Oz46P/rLpqTDz7hkde9+O1IniTnCXrbQj602f9gJcAT0x7FxsqiEyjqevA4WLyrLgxIG1+",
	"uIBqalYF/Mnv3x0d+MJXbagym7Di4GBzVpS1z3LDggneB5YyfOBs655lLzCo890suyqY5RaSLFkGRlhq",
	"G3F5p7XKrcPjtdWLnOJed0m2rO68EaY3YnPcFqnCwJJMwTwDVFNsWzCMczsaUf2IixHvHvuPjz3Y37rt",
	"9KvPttdJFGkk+wKeQBAqY7mM+C9ZvmePJX+EpSZUAQntUtuNsg2iuYinfW2WAjA6NaCkJv8Ag/mAgAzV",
	"MkHY/dM/Dsi9BiJTIRDCTMUJoflWmKspEMtGR+Y1gIhygc7s/PaPI9smKXcMznCzlUcc8BKK1OcT76zj",
	"cISbmGTryEzFkRcfXwKaMm4eRDy3mQtEyQNye5uaZC/A7T1RQBZ1lDl5tXXBJfkT/BJSQWt43UhVKsUQ",
	"BjNqjeqXIEmngodBy/TfutXID9c4Azzcz41sj15AJRVLw0O9HSdM7MkhPDWmjZixQ5/MSsKS4dPiehWw",
	"Reg4D894FAHj1IBYkucFSPSWbkCiLBFyXRQH2wprqH588BUz7juLF7UBjL2PUtS5lJPXxaNKnOKxdFGE",
	"Jo6DYJroBUX5TZc2nK2WO8twlvw7snDivp8g4yaFC5nYuxdc7WdNybAMOOxB+FASJ6mgyG7PhjPKRb7b",
	"xAaJ3ic9JaeClA0c58nmjjMrF+3XG0OebmxQf908zM4Eli+vBdco0C2Cnkq4INPIGhSwlXA7VPSQF7xt",
	"L7sMIpzwEI0bBhkV9fqVNKW4Wk2y/uYtlzOPFTy/ubS6HlFJ53lg4GKBJ05z82e5yo29UPYVOb+5DCpF",
	"juBgcDA4RDbECUiacLz74GBwHLgqk2X/sNh9SJllVJLV4JrF1Uobo7DIGg0evLjusW+kKes+o7m0a2kt",
	"oy+7oUXRtlGYtrQ7lb9kyBzGLsoCXDn0tewCe20ubNgcCmvOKB0dHHZvlK0brhl8WPWC44OD9dtU5qHs",
	"I39Y/0gxXLTqBSebnOFr7NsmSRpFVC2tK3OSdILk2g52tSSKYKNzjUAv8BJ8xZ0q+HF474bQpeSG2/Eh",
	"VquVW5g02mTjHDLOVVxeuPJOSCWZAkliIYBZdZj8NLojLSKG+JQevrphxNWkkaZayNmNnfOo1KW6Iepp",
	"mzTRWW84fR+AHq2Xeq0x+v8Ljo6DhFpuWwtYsQlboLABACRtDh5M3sRCuK5Y5txsScFCg2dwtUHL5Ob6",
	"1oOzyQYxSyNAqZRAJ35LMtkKcz+B6exz9mrj0h11p3LJMJvdXX1toe5gbw32TmJ9jeBW0bne+6zUoRxo",
	"j9djsBju2R9ofwLTglCD0Cxcz+Fr0dmCbjFVUoFrS9jNmZ3AL6u379Q5+LM/pnzm2thYf82sTDGQs4ly",
	"v7Lp5cVqWMYX/Wwk1KvcuRNB2czemBLtHnTsdU2Q/kwlE9k0V0gVkP/97/8hxo6VGjdDaxnVnjFtybPS",
	"1y3HZrfWXPvuQpferrXinnndH0CdPFKi2/mCDC6unePwUX5aE5oU/am9hSY1anaPUGoNszwZ84Gr3nbc",
	"G6R2CkB+GyQ5DlTHUqZLN2O9JXb2Hk5cjD6P7kad6PjWuMLbP510WaCu9vRuiOn9EGFG56U2CjPqre0f",
	"OMxoELpRmJEhzdZ0MVlLPUC+U3w+t/l9pb+m0v1bQ9xu+OpebFvtbBSLd+eKFiDJ+ObD/KjezvwWy1hL",
	"73Z8bcBX/r28aL0S6NoUlvLvMYbbVovLvPasyfOChwsvKd531n6jlHVLtTw+2oAw36zt/lQ6U7MKbOst",
	"bY+n6lu9fUOnh+hpNi3kuTSlrubVkh3PCiDcaNIayfQVP/auVOtrJs03JHcq6rWm8n8lEH6PukkpyrUx",
	"83o0FbZ5fRRdh5ZbpZtvifpi1G8EzfqII3tx2hNxHPuv4djnnwP7EQLab7MQHf52D1Wy+y4f/40RrWc8",
	"KC+TvTlZ5Al3/eNZ3xt5P0ZU7L/7JiGxJI0hsB83KG6Tum1YXCqIe/OoM0yuWzy3uNuZIp35q0wKwlgx",
	"H0Tv7Ypf1yTu3eMe/M17XCemWttsU6O8sC8cdxZ5Py4gfHQvJe9U3G28z7zHIAMJyxvQZJFTmF81+8K9",
	"z+desXWItTXaYGFMos+GwyhrYEswQ5pwi8Bsi3YB1zUne1mc2rPq5NpCvm6znYjL/zWXorKDyuAfwnPq",
	"abIgvBCfbo/heTZ2Em1v/ucU1LJqk5wJsAkrmqf6eFB1Z2eX2jvmr3U7Btv9sndLueBmWdkhE8Hq6+r/",
	"AgAA//+ELOzxOEcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
