// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DoneEventEvent.
const (
	Done DoneEventEvent = "done"
)

// Valid indicates whether the value is a known member of the DoneEventEvent enum.
func (e DoneEventEvent) Valid() bool {
	switch e {
	case Done:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEventEvent.
const (
	ErrorEventEventError ErrorEventEvent = "error"
)

// Valid indicates whether the value is a known member of the ErrorEventEvent enum.
func (e ErrorEventEvent) Valid() bool {
	switch e {
	case ErrorEventEventError:
		return true
	default:
		return false
	}
}

// Defines values for TaskUpdateEvent.
const (
	Message TaskUpdateEvent = "message"
)

// Valid indicates whether the value is a known member of the TaskUpdateEvent enum.
func (e TaskUpdateEvent) Valid() bool {
	switch e {
	case Message:
		return true
	default:
		return false
	}
}

// DatabaseAcknowledgment Confirmation returned after a database is successfully created or registered. Contains only the system-assigned ID.
type DatabaseAcknowledgment struct {
	// Id System-assigned unique identifier for the new database
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

// DatabaseConfig Connection configuration for a database.
type DatabaseConfig struct {
	// Alias Optional human-friendly label
	Alias  *string `json:"alias,omitempty"`
	Engine string  `json:"engine"`
	Host   string  `json:"host"`

	// Image The docker image to use
	Image    *string `json:"image,omitempty"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`

	// Path Optional filesystem path for local/embedded engines
	Path *string `json:"path,omitempty"`
	Port string  `json:"port"`

	// Role Database role for connection
	Role     *string `json:"role,omitempty"`
	SslMode  *string `json:"ssl_mode,omitempty"`
	Username string  `json:"username"`
	Version  *string `json:"version,omitempty"`
}

// DoneEvent defines model for DoneEvent.
type DoneEvent struct {
	Data  *string         `json:"data,omitempty"`
	Event *DoneEventEvent `json:"event,omitempty"`
}

// DoneEventEvent defines model for DoneEvent.Event.
type DoneEventEvent string

// Error Standard error envelope returned for all 4xx and 5xx responses.
type Error struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Details Optional additional context about the error
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable description of the error
	Message string `json:"message"`
}

// ErrorEvent defines model for ErrorEvent.
type ErrorEvent struct {
	Data *struct {
		Message *string `json:"message,omitempty"`
		Status  *string `json:"status,omitempty"`
	} `json:"data,omitempty"`
	Event *ErrorEventEvent `json:"event,omitempty"`
}

// ErrorEventEvent defines model for ErrorEvent.Event.
type ErrorEventEvent string

// SyncRuleConfig Configuration for syncing data between databases with optional masking rules.
type SyncRuleConfig struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

// TaskReference Returned immediately when an async operation is accepted.
type TaskReference struct {
	// TaskId Unique identifier for the async task
	TaskId openapi_types.UUID `json:"task_id"`
}

// TaskUpdate Task Update
type TaskUpdate struct {
	Data *struct {
		Message *string `json:"message,omitempty"`
		Status  *string `json:"status,omitempty"`
	} `json:"data,omitempty"`
	Event *TaskUpdateEvent `json:"event,omitempty"`
}

// TaskUpdateEvent defines model for TaskUpdate.Event.
type TaskUpdateEvent string

// DbID defines model for dbID.
type DbID = int64

// SyncID defines model for syncID.
type SyncID = int64

// TaskID defines model for taskID.
type TaskID = openapi_types.UUID

// BadRequest Standard error envelope returned for all 4xx and 5xx responses.
type BadRequest = Error

// Conflict Standard error envelope returned for all 4xx and 5xx responses.
type Conflict = Error

// ConnectionUrlResponse defines model for ConnectionUrlResponse.
type ConnectionUrlResponse struct {
	// ConnectionUrl Fully-formed connection URL including credentials. Treat as a secret.
	ConnectionUrl string `json:"connection_url"`

	// Id Database ID
	Id int64 `json:"id"`
}

// DatabaseAcknowledgmentResponse Confirmation returned after a database is successfully created or registered. Contains only the system-assigned ID.
type DatabaseAcknowledgmentResponse = DatabaseAcknowledgment

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string  `json:"status"`
	Version *string `json:"version,omitempty"`
}

// InternalServerError Standard error envelope returned for all 4xx and 5xx responses.
type InternalServerError = Error

// NotFound Standard error envelope returned for all 4xx and 5xx responses.
type NotFound = Error

// SyncRuleResponse defines model for SyncRuleResponse.
type SyncRuleResponse struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Id System-assigned sync rule identifier
	Id int64 `json:"id"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

// TaskAccepted Returned immediately when an async operation is accepted.
type TaskAccepted = TaskReference

// UnprocessableEntity Standard error envelope returned for all 4xx and 5xx responses.
type UnprocessableEntity = Error

// DatabaseRequest Connection configuration for a database.
type DatabaseRequest = DatabaseConfig

// SyncRuleRequest Configuration for syncing data between databases with optional masking rules.
type SyncRuleRequest = SyncRuleConfig

// ExecuteSyncRuleJSONBody defines parameters for ExecuteSyncRule.
type ExecuteSyncRuleJSONBody struct {
	// Id ID of the sync rule to execute
	Id int64 `json:"id"`
}

// AddDatabaseJSONRequestBody defines body for AddDatabase for application/json ContentType.
type AddDatabaseJSONRequestBody = DatabaseConfig

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = DatabaseConfig

// ExecuteSyncRuleJSONRequestBody defines body for ExecuteSyncRule for application/json ContentType.
type ExecuteSyncRuleJSONRequestBody ExecuteSyncRuleJSONBody

// CreateSyncRuleJSONRequestBody defines body for CreateSyncRule for application/json ContentType.
type CreateSyncRuleJSONRequestBody = SyncRuleConfig

// UpdateSyncRuleJSONRequestBody defines body for UpdateSyncRule for application/json ContentType.
type UpdateSyncRuleJSONRequestBody = SyncRuleConfig

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register an existing external database
	// (POST /databases/add)
	AddDatabase(w http.ResponseWriter, r *http.Request)
	// Create a new managed database
	// (POST /databases/create)
	CreateDatabase(w http.ResponseWriter, r *http.Request)
	// List all supported database engines and versions
	// (GET /databases/supported)
	GetSupportedEngines(w http.ResponseWriter, r *http.Request)
	// Get the connection URL for a database
	// (GET /databases/{dbID}/connection-url)
	GetDatabaseConnectionUrl(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Delete a database by ID
	// (DELETE /databases/{dbID}/delete)
	DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Trigger execution of a sync rule
	// (PUT /databases/{dbID}/sync)
	ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Create a new sync rule for a database
	// (POST /databases/{dbID}/sync/init)
	CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Delete a sync rule
	// (DELETE /databases/{dbID}/sync/{syncID}/delete)
	DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID)
	// Update an existing sync rule
	// (PUT /databases/{dbID}/sync/{syncID}/update)
	UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID)
	// Check Mezcala health
	// (GET /health)
	CheckHealth(w http.ResponseWriter, r *http.Request)
	// Get the updates of a task
	// (GET /tasks/{taskID})
	GetTaskUpdates(w http.ResponseWriter, r *http.Request, taskID TaskID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register an existing external database
// (POST /databases/add)
func (_ Unimplemented) AddDatabase(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new managed database
// (POST /databases/create)
func (_ Unimplemented) CreateDatabase(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all supported database engines and versions
// (GET /databases/supported)
func (_ Unimplemented) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the connection URL for a database
// (GET /databases/{dbID}/connection-url)
func (_ Unimplemented) GetDatabaseConnectionUrl(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a database by ID
// (DELETE /databases/{dbID}/delete)
func (_ Unimplemented) DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger execution of a sync rule
// (PUT /databases/{dbID}/sync)
func (_ Unimplemented) ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new sync rule for a database
// (POST /databases/{dbID}/sync/init)
func (_ Unimplemented) CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a sync rule
// (DELETE /databases/{dbID}/sync/{syncID}/delete)
func (_ Unimplemented) DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing sync rule
// (PUT /databases/{dbID}/sync/{syncID}/update)
func (_ Unimplemented) UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check Mezcala health
// (GET /health)
func (_ Unimplemented) CheckHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the updates of a task
// (GET /tasks/{taskID})
func (_ Unimplemented) GetTaskUpdates(w http.ResponseWriter, r *http.Request, taskID TaskID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AddDatabase operation middleware
func (siw *ServerInterfaceWrapper) AddDatabase(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddDatabase(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDatabase operation middleware
func (siw *ServerInterfaceWrapper) CreateDatabase(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDatabase(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupportedEngines operation middleware
func (siw *ServerInterfaceWrapper) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupportedEngines(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDatabaseConnectionUrl operation middleware
func (siw *ServerInterfaceWrapper) GetDatabaseConnectionUrl(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDatabaseConnectionUrl(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDatabase operation middleware
func (siw *ServerInterfaceWrapper) DeleteDatabase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDatabase(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteSyncRule operation middleware
func (siw *ServerInterfaceWrapper) ExecuteSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteSyncRule(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSyncRule operation middleware
func (siw *ServerInterfaceWrapper) CreateSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSyncRule(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSyncRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	// ------------- Path parameter "syncID" -------------
	var syncID SyncID

	err = runtime.BindStyledParameterWithOptions("simple", "syncID", chi.URLParam(r, "syncID"), &syncID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "syncID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSyncRule(w, r, dbid, syncID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSyncRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	// ------------- Path parameter "syncID" -------------
	var syncID SyncID

	err = runtime.BindStyledParameterWithOptions("simple", "syncID", chi.URLParam(r, "syncID"), &syncID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "syncID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSyncRule(w, r, dbid, syncID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckHealth operation middleware
func (siw *ServerInterfaceWrapper) CheckHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckHealth(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskUpdates operation middleware
func (siw *ServerInterfaceWrapper) GetTaskUpdates(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskID" -------------
	var taskID TaskID

	err = runtime.BindStyledParameterWithOptions("simple", "taskID", chi.URLParam(r, "taskID"), &taskID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskUpdates(w, r, taskID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/add", wrapper.AddDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/create", wrapper.CreateDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/databases/supported", wrapper.GetSupportedEngines)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/databases/{dbID}/connection-url", wrapper.GetDatabaseConnectionUrl)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/databases/{dbID}/delete", wrapper.DeleteDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/databases/{dbID}/sync", wrapper.ExecuteSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/{dbID}/sync/init", wrapper.CreateSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/databases/{dbID}/sync/{syncID}/delete", wrapper.DeleteSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/databases/{dbID}/sync/{syncID}/update", wrapper.UpdateSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.CheckHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tasks/{taskID}", wrapper.GetTaskUpdates)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ConnectionUrlResponseJSONResponse struct {
	// ConnectionUrl Fully-formed connection URL including credentials. Treat as a secret.
	ConnectionUrl string `json:"connection_url"`

	// Id Database ID
	Id int64 `json:"id"`
}

type DatabaseAcknowledgmentResponseJSONResponse DatabaseAcknowledgment

type HealthResponseJSONResponse struct {
	Status  string  `json:"status"`
	Version *string `json:"version,omitempty"`
}

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type SyncRuleResponseJSONResponse struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Id System-assigned sync rule identifier
	Id int64 `json:"id"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

type TaskAcceptedJSONResponse TaskReference

type UnprocessableEntityJSONResponse Error

type AddDatabaseRequestObject struct {
	Body *AddDatabaseJSONRequestBody
}

type AddDatabaseResponseObject interface {
	VisitAddDatabaseResponse(w http.ResponseWriter) error
}

type AddDatabase201JSONResponse struct {
	DatabaseAcknowledgmentResponseJSONResponse
}

func (response AddDatabase201JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase400JSONResponse struct{ BadRequestJSONResponse }

func (response AddDatabase400JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase409JSONResponse struct{ ConflictJSONResponse }

func (response AddDatabase409JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AddDatabase500JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabaseRequestObject struct {
	Body *CreateDatabaseJSONRequestBody
}

type CreateDatabaseResponseObject interface {
	VisitCreateDatabaseResponse(w http.ResponseWriter) error
}

type CreateDatabase202JSONResponse struct{ TaskAcceptedJSONResponse }

func (response CreateDatabase202JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateDatabase400JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase409JSONResponse struct{ ConflictJSONResponse }

func (response CreateDatabase409JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateDatabase500JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSupportedEnginesRequestObject struct {
}

type GetSupportedEnginesResponseObject interface {
	VisitGetSupportedEnginesResponse(w http.ResponseWriter) error
}

type GetSupportedEngines200JSONResponse []struct {
	Engine   string   `json:"engine"`
	Versions []string `json:"versions"`
}

func (response GetSupportedEngines200JSONResponse) VisitGetSupportedEnginesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSupportedEngines500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetSupportedEngines500JSONResponse) VisitGetSupportedEnginesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDatabaseConnectionUrlRequestObject struct {
	DbID DbID `json:"dbID"`
}

type GetDatabaseConnectionUrlResponseObject interface {
	VisitGetDatabaseConnectionUrlResponse(w http.ResponseWriter) error
}

type GetDatabaseConnectionUrl200JSONResponse struct {
	ConnectionUrlResponseJSONResponse
}

func (response GetDatabaseConnectionUrl200JSONResponse) VisitGetDatabaseConnectionUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDatabaseConnectionUrl404JSONResponse struct{ NotFoundJSONResponse }

func (response GetDatabaseConnectionUrl404JSONResponse) VisitGetDatabaseConnectionUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDatabaseConnectionUrl500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetDatabaseConnectionUrl500JSONResponse) VisitGetDatabaseConnectionUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDatabaseRequestObject struct {
	DbID DbID `json:"dbID"`
}

type DeleteDatabaseResponseObject interface {
	VisitDeleteDatabaseResponse(w http.ResponseWriter) error
}

type DeleteDatabase202JSONResponse struct{ TaskAcceptedJSONResponse }

func (response DeleteDatabase202JSONResponse) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDatabase404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteDatabase404JSONResponse) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteDatabase500JSONResponse) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRuleRequestObject struct {
	DbID DbID `json:"dbID"`
	Body *ExecuteSyncRuleJSONRequestBody
}

type ExecuteSyncRuleResponseObject interface {
	VisitExecuteSyncRuleResponse(w http.ResponseWriter) error
}

type ExecuteSyncRule202JSONResponse struct{ TaskAcceptedJSONResponse }

func (response ExecuteSyncRule202JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response ExecuteSyncRule400JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response ExecuteSyncRule404JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ExecuteSyncRule422JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ExecuteSyncRule500JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRuleRequestObject struct {
	DbID DbID `json:"dbID"`
	Body *CreateSyncRuleJSONRequestBody
}

type CreateSyncRuleResponseObject interface {
	VisitCreateSyncRuleResponse(w http.ResponseWriter) error
}

type CreateSyncRule201JSONResponse struct{ SyncRuleResponseJSONResponse }

func (response CreateSyncRule201JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSyncRule400JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateSyncRule404JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateSyncRule500JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSyncRuleRequestObject struct {
	DbID   DbID   `json:"dbID"`
	SyncID SyncID `json:"syncID"`
}

type DeleteSyncRuleResponseObject interface {
	VisitDeleteSyncRuleResponse(w http.ResponseWriter) error
}

type DeleteSyncRule204Response struct {
}

func (response DeleteSyncRule204Response) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSyncRule404JSONResponse) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteSyncRule500JSONResponse) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRuleRequestObject struct {
	DbID   DbID   `json:"dbID"`
	SyncID SyncID `json:"syncID"`
	Body   *UpdateSyncRuleJSONRequestBody
}

type UpdateSyncRuleResponseObject interface {
	VisitUpdateSyncRuleResponse(w http.ResponseWriter) error
}

type UpdateSyncRule200JSONResponse struct{ SyncRuleResponseJSONResponse }

func (response UpdateSyncRule200JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSyncRule400JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateSyncRule404JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateSyncRule500JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealthRequestObject struct {
}

type CheckHealthResponseObject interface {
	VisitCheckHealthResponse(w http.ResponseWriter) error
}

type CheckHealth200JSONResponse struct{ HealthResponseJSONResponse }

func (response CheckHealth200JSONResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealth500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CheckHealth500JSONResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskUpdatesRequestObject struct {
	TaskID TaskID `json:"taskID"`
}

type GetTaskUpdatesResponseObject interface {
	VisitGetTaskUpdatesResponse(w http.ResponseWriter) error
}

type GetTaskUpdates200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetTaskUpdates200TexteventStreamResponse) VisitGetTaskUpdatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register an existing external database
	// (POST /databases/add)
	AddDatabase(ctx context.Context, request AddDatabaseRequestObject) (AddDatabaseResponseObject, error)
	// Create a new managed database
	// (POST /databases/create)
	CreateDatabase(ctx context.Context, request CreateDatabaseRequestObject) (CreateDatabaseResponseObject, error)
	// List all supported database engines and versions
	// (GET /databases/supported)
	GetSupportedEngines(ctx context.Context, request GetSupportedEnginesRequestObject) (GetSupportedEnginesResponseObject, error)
	// Get the connection URL for a database
	// (GET /databases/{dbID}/connection-url)
	GetDatabaseConnectionUrl(ctx context.Context, request GetDatabaseConnectionUrlRequestObject) (GetDatabaseConnectionUrlResponseObject, error)
	// Delete a database by ID
	// (DELETE /databases/{dbID}/delete)
	DeleteDatabase(ctx context.Context, request DeleteDatabaseRequestObject) (DeleteDatabaseResponseObject, error)
	// Trigger execution of a sync rule
	// (PUT /databases/{dbID}/sync)
	ExecuteSyncRule(ctx context.Context, request ExecuteSyncRuleRequestObject) (ExecuteSyncRuleResponseObject, error)
	// Create a new sync rule for a database
	// (POST /databases/{dbID}/sync/init)
	CreateSyncRule(ctx context.Context, request CreateSyncRuleRequestObject) (CreateSyncRuleResponseObject, error)
	// Delete a sync rule
	// (DELETE /databases/{dbID}/sync/{syncID}/delete)
	DeleteSyncRule(ctx context.Context, request DeleteSyncRuleRequestObject) (DeleteSyncRuleResponseObject, error)
	// Update an existing sync rule
	// (PUT /databases/{dbID}/sync/{syncID}/update)
	UpdateSyncRule(ctx context.Context, request UpdateSyncRuleRequestObject) (UpdateSyncRuleResponseObject, error)
	// Check Mezcala health
	// (GET /health)
	CheckHealth(ctx context.Context, request CheckHealthRequestObject) (CheckHealthResponseObject, error)
	// Get the updates of a task
	// (GET /tasks/{taskID})
	GetTaskUpdates(ctx context.Context, request GetTaskUpdatesRequestObject) (GetTaskUpdatesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AddDatabase operation middleware
func (sh *strictHandler) AddDatabase(w http.ResponseWriter, r *http.Request) {
	var request AddDatabaseRequestObject

	var body AddDatabaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddDatabase(ctx, request.(AddDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddDatabaseResponseObject); ok {
		if err := validResponse.VisitAddDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDatabase operation middleware
func (sh *strictHandler) CreateDatabase(w http.ResponseWriter, r *http.Request) {
	var request CreateDatabaseRequestObject

	var body CreateDatabaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDatabase(ctx, request.(CreateDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDatabaseResponseObject); ok {
		if err := validResponse.VisitCreateDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSupportedEngines operation middleware
func (sh *strictHandler) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {
	var request GetSupportedEnginesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSupportedEngines(ctx, request.(GetSupportedEnginesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSupportedEngines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSupportedEnginesResponseObject); ok {
		if err := validResponse.VisitGetSupportedEnginesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDatabaseConnectionUrl operation middleware
func (sh *strictHandler) GetDatabaseConnectionUrl(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request GetDatabaseConnectionUrlRequestObject

	request.DbID = dbid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDatabaseConnectionUrl(ctx, request.(GetDatabaseConnectionUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDatabaseConnectionUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDatabaseConnectionUrlResponseObject); ok {
		if err := validResponse.VisitGetDatabaseConnectionUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDatabase operation middleware
func (sh *strictHandler) DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request DeleteDatabaseRequestObject

	request.DbID = dbid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDatabase(ctx, request.(DeleteDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDatabaseResponseObject); ok {
		if err := validResponse.VisitDeleteDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExecuteSyncRule operation middleware
func (sh *strictHandler) ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request ExecuteSyncRuleRequestObject

	request.DbID = dbid

	var body ExecuteSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExecuteSyncRule(ctx, request.(ExecuteSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExecuteSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExecuteSyncRuleResponseObject); ok {
		if err := validResponse.VisitExecuteSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSyncRule operation middleware
func (sh *strictHandler) CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request CreateSyncRuleRequestObject

	request.DbID = dbid

	var body CreateSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSyncRule(ctx, request.(CreateSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSyncRuleResponseObject); ok {
		if err := validResponse.VisitCreateSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSyncRule operation middleware
func (sh *strictHandler) DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	var request DeleteSyncRuleRequestObject

	request.DbID = dbid
	request.SyncID = syncID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSyncRule(ctx, request.(DeleteSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSyncRuleResponseObject); ok {
		if err := validResponse.VisitDeleteSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSyncRule operation middleware
func (sh *strictHandler) UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	var request UpdateSyncRuleRequestObject

	request.DbID = dbid
	request.SyncID = syncID

	var body UpdateSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSyncRule(ctx, request.(UpdateSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSyncRuleResponseObject); ok {
		if err := validResponse.VisitUpdateSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckHealth operation middleware
func (sh *strictHandler) CheckHealth(w http.ResponseWriter, r *http.Request) {
	var request CheckHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckHealth(ctx, request.(CheckHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckHealthResponseObject); ok {
		if err := validResponse.VisitCheckHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTaskUpdates operation middleware
func (sh *strictHandler) GetTaskUpdates(w http.ResponseWriter, r *http.Request, taskID TaskID) {
	var request GetTaskUpdatesRequestObject

	request.TaskID = taskID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskUpdates(ctx, request.(GetTaskUpdatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskUpdates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTaskUpdatesResponseObject); ok {
		if err := validResponse.VisitGetTaskUpdatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xb/W4jtxF/FWJbIG2hD9tn+xoDRes76xIhF/si2wWKq+FQy5HEmEtuSK5txTDQh+gT",
	"9kmKIblfWuokO74c2r9OlsjhcOY337yHJFVZriRIa5KjhySnmmZgQbu/2HR84v4Fk2qeW65kcpRcSv5z",
	"AYQzkJbPOGiiZsQugDBq6ZQaSHoJx4U5tYukl0iaQXLkifUSDT8XXANLjqwuoJeYdAEZxVPgnma5gORo",
	"f6+XzJTOqE2OEi7t4X7SS+wyB/8nzEEnj4+9xCxl+iQGcQPRhVjDYaC3FY+vt2PRUnPzJBap4xG3xXkM",
	"BLfiMXk1o38+mB3u9w9e777u7x8c7vWnr2Zpfy/9+vDV7PCQzuhh0rhIUXBW38NYzeU8ecR74Glg7BvF",
	"ODhonARdT/wP+FWqpAXpPtI8FzyleNnhTwZv/NBg8PcaZslR8rthjb2h/9UMS7pvlZzxcHhbdB/oUijK",
	"yExpomHOjQXkkyhNUg3U4mdaYZGkSkpIce+gI7XHXnK+lOmkEC9+j5LudveoGFeaFDkrL1HhNcK6U4rJ",
	"lTReIW8o2/4OFURwJUNlvzk+uZ6MfrgcnV8kvSQDY+gcv3/HQTDyFcg5l/AV4YaUfAySx96WwhhprXRM",
	"BhcLIAFaSDqjArEIDOUwo1wYcksFZ9Sr77GXoDgFT593x7dnp+/ej9+2L3hcQ+WO2wWxC24IGhuhQgNl",
	"SwL33Fjzctc1qtDpKnm88S1XglowhJLC+QcJxiCAjdWUS1tKIOD5UotJQMCTYJtrlYO2wZBr+7gutOh6",
	"qneFEMt+UEu9mFxO3hMuU1EwxGqqwbkyKsyAXCCaCcV7GEg12ME/ZdJr+KVcGTvXYI6GQ8oyLo/Mq1S/",
	"sn9j00FYNEhVdnSw/2pvmC37pYL+aozIFIO/BAh2XVUv4ax7hdKnEOc4nxxmasP7mDj/uCKyq2qXmv4E",
	"qV2n+RXhod27oJRDiiGAVUB0ei6ZPk5vpLoTwOYZSPsshW/jb9vHrLtCbSrUVM7Xm6tzYcCIKdIUjJkh",
	"bNxFvgUq7OIFkGostYX71NH6LWjDV8w+2R3sDV5Fwllbo4HqNko8B33LU/BOkKYLOhVAqGREQ660NYRb",
	"Q9JCa5CWeLpOAmNpQUsqcD9o7x2e47/Gpxejyenx++vz0eTvo8n1aDI5m7SdmSSFhPscUlQF4ElEpY4l",
	"NiAfBKDurF4SOqdcEvQ2+iUcW/tc4+7ZN5zBKg941qmy71Qh2bNkcHp2cf3u7PL0pHXvkxUXDmTOb0GS",
	"8YlDqlSWzPDIF45ZwGp3zhT4g5w/dwfVucUzsE+FOJslRx+flmb0Vo0m5g/Pl8ZC1qfG8LlEfZVpRiMf",
	"bTrK18/yk12LulrnGIPrKJOfJktOkBfU3BynKeQW2It5PiQ6gRlokCmsUzSK0hEnC2rIFEASGhhxlo+u",
	"oJDSpWvI80IrqQojlgPyQQnhoJgq7TM1FykxgQ/OgYBkueLSEquI1TS9IblWGBgNRszHXnIpc63QnaKr",
	"GUnL7fJZVnN5+mFy9nZ0fn785v3oenR6Mb74R8uAzkNOIhlhYCyX/tKlvzckpRLBPQUfs2gGnyH/uwMh",
	"ylRjWliMmJZyaYiBjErLU+9O0KtWZ7eqkZUo1kG+MxNEMl5Ogy004p/OLOhmzcBNK4w1AVoHvQF5W7Kn",
	"pFiGArNtWeMTn/o83SaLToFY5gsS7pqV9tPSmYbOm6Gy8p/xKL4phrqsqCTctfs6mQluKqaXMjVK3ZIi",
	"WB1emjYSo1VRUsE9Atr0ztwHKsiiyKjszzQHycSSCDoF0U5FtWJ9No2lkr7maQuqzFxj6xfK11716nY+",
	"G01Xs6CLSK6l0hvQxK1AB1G01V0n0bsHMcq+X9DkppFJxzbk1Jg7pVl7k8/Mm02Cal2Uhl18QhszLsCb",
	"CMGVTrtCpVQMIZsCY5izOKGb1k2Ht1QPBZ8Os2VcU5h9tdnG0iG2UisBnygQ8GdfkFeAbHGCFRsae4y0",
	"MeI6c+72obVjbalSGMwKV7XkCqLY8niOe7DROAOMAz6DsBqnNzQfNV0lYXQbvGnb+BBNbXY+npydjq6i",
	"xlSSAFlkyBZTsukrGsx3WKgy5hWXaalkVJd5LshbECqH2q875yEE2b+/d5Ht4P6eVD2Tri9Jg/Lap3xP",
	"0wWX0EfVu4Tfn+YWN6HRTEw7t2dgKRfeYzHGvTl8aJzue3hrzKbe4iIi3FtCp6qwLhw4dpKI1BqOvk33",
	"W+cTq/s0fiybkCXN+nZrkt6V5HoTFIPQPhUpnK434K39beOeXZtcVzLGYNaBqBfDdhhdScTjmUcrrGG6",
	"iAkh3opMwd5hclknXK6SUSUEMmpucDGmxBHo4rZr99t6iD3EYNlmURSZ7Au4BUGoVHKZ8V9CquSOJd/B",
	"0hCqMaXFpa5N5jpXc6GmfWOXAtCxY7VryB9gMB8QkKleYrp8/ac/DsilASILzIsVYVrlhJakMM3RIJYr",
	"raKHBDLKBdrh8fl3I9e/qSkmR0gsqsv7VBQxc75wmPeMW0XCOjLTKqtGBE0GPia0YNxeCzV3QR+y/Nrh",
	"8KqXcAtZXLDhC6o1XeLfSD7iwELlWLenmj0VLsn38EtKBW3ys7tVktdIjRnMaCEs3iQvpoKnyPkKH341",
	"ysN39AAPj0sj0OglVFKxtDw1T5OEVZHwG6k4thLGMxp4ThOOjZj3adeEHUYnZWThWQaMUwtiSe4WWBTK",
	"MLmpC0ZuqlKxa7BYBV7H6oDLtXl/azL04jOetpRK9tbJ6NKV6THrMjck/Nj7wt67G2XWb8evuJxFsHn8",
	"Yew0kFFJ56W79h76ltMSlC70cesUEr4ixx/GSSNrS3YGO4Nd5FTlIGnOUXeDncF+4tNmd89hRX1ImUNH",
	"HoqK1Wqx0Wqo7MQgDOHeNxtjE7DQrEQQu7W0VS7XzbOqCm1Yo3fMFbzHDIXD2EldUdQzwuW6hkBrjDhc",
	"nSGujrT2dnbXEwrrhhv65I+9ZH9nZzOZxvjMbfl685ZqFvXYSw62OSPWB3aNjCLLqF46B+M16RXJjZsD",
	"djSKYKNz47LoEi/JFVJq4MdX8ushNJbccjdtYq3i38FkpZU1KSHju1fjE2IX1JKUSjIFkishgGH0SBeQ",
	"3vjA4Uw3Apm3jq3Pi5q9zapodRT/tzDiJUioawQ5t9Qw1K2gYYoci0DfS52DA0dbS9+APS8XjaqKfEXM",
	"O09qxVYpQtv/P7XJEvypae34mOyiG3XF8O7hUxKSdbVydUwsAq6Q6CTSXmLO2VZ0Xk7/77mxrqyt1Fhb",
	"cOietI/eBhIPbDo+eRzWoaIfhsEBHrE8yDhLn31iPrx+xNlbNzv+lkomwhwnxVLjP//6N7FuoGz99NwJ",
	"qjtd7gC40XOsB+Yu2NZPnNZMV+olQ/dq6fEqDv6Nth+Z1DvPsb95dzUleznkfAM2DCQ6WqJP8yABLgwE",
	"lGlg/WlDlHFLnx1lMOn68ZvRBVnHzRA3m+GDfyj1+OOAnEmCAgunogAcfQ2mEI0ZA/Wt53I6ENLHGLhO",
	"3EGNGPYykHpW2PoySPISaI5Mpkv/umJr7LjSEsNBEXEwF5rP5y6hbQwnddHBTEQ5o3tICwtlP+bXaKeV",
	"mDzz0UKsxhufdB4k+l6E4/xzTF67MWpcFpiG3C14uoiyEn0x94WSrScCfX9vC8Zi49WXM5IA4iDM0F6l",
	"rUeoq9bSd1bxCYsZcsnttnWhLwHaRtSsAHko+bg1pDOyjKXtL25Um7P91feZz6oROw8xfiMQfo6Mv1bl",
	"xri9GU0P/snzNpG8DS2/yqy+UY3FyV8Jmt7GdeHZdiSi7sev4cXnrxB5sPbFg+qv8xCVTouqSReNsW2F",
	"+sXrfQVGq/JxjoZUaRZzE77199tq/MUdys7/vUPxamo1mbbF3MK95lzbOHi7gPTGv/hMniPYlceiL+hD",
	"XWuq7M0uSg7Lq4Yv/B3bFcTaKrgsp0rTcdE99Oc71WjdNTdPNovwfz7WVaGNzNTCvR26TnjfYNGctVNT",
	"JWGLN4WNBv86W2w97PLT2k1L63cE8XeAWJIVLHcCipetXTk7Ov61qReka1okC2tzczQcZqE5L8EOac6d",
	"AIPCux0N33jthaSp55yf767FOuluBlv+x6aq1EEZxMe+3pnakBFWxma6g98IYW9/XeI/FKCXjXZrcNiu",
	"rEUhtQdSTcoO4RGK5Qtnbw6OHr2lXNApF9wuGxSCwTxePf43AAD//4gkhCJDNgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
