// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// DatabaseConnectionConfig Connection properties for a database.
type DatabaseConnectionConfig struct {
	// Alias Optional human-friendly label
	Alias    *string `json:"alias,omitempty"`
	Engine   string  `json:"engine"`
	Host     string  `json:"host"`
	Name     string  `json:"name"`
	Password string  `json:"password"`

	// Path Optional filesystem path for local/embedded engines
	Path *string `json:"path,omitempty"`
	Port string  `json:"port"`

	// Role Database role for connection
	Role     *string `json:"role,omitempty"`
	SslMode  *string `json:"ssl_mode,omitempty"`
	Username string  `json:"username"`
	Version  string  `json:"version"`
}

// Error Standard error envelope returned for all 4xx and 5xx responses.
type Error struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Details Optional additional context about the error
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable description of the error
	Message string `json:"message"`
}

// SyncRuleConfig Configuration for syncing data between databases with optional masking rules.
type SyncRuleConfig struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

// DbID defines model for dbID.
type DbID = int64

// SyncID defines model for syncID.
type SyncID = int64

// BadRequest Standard error envelope returned for all 4xx and 5xx responses.
type BadRequest = Error

// Conflict Standard error envelope returned for all 4xx and 5xx responses.
type Conflict = Error

// DatabaseResponse defines model for DatabaseResponse.
type DatabaseResponse struct {
	// Alias Optional human-friendly label
	Alias  *string `json:"alias,omitempty"`
	Engine string  `json:"engine"`
	Host   string  `json:"host"`

	// Id System-assigned unique identifier
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`

	// Path Optional filesystem path for local/embedded engines
	Path *string `json:"path,omitempty"`
	Port string  `json:"port"`

	// Role Database role for connection
	Role     *string `json:"role,omitempty"`
	SslMode  *string `json:"ssl_mode,omitempty"`
	Username string  `json:"username"`
	Version  string  `json:"version"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string  `json:"status"`
	Version *string `json:"version,omitempty"`
}

// InternalServerError Standard error envelope returned for all 4xx and 5xx responses.
type InternalServerError = Error

// NotFound Standard error envelope returned for all 4xx and 5xx responses.
type NotFound = Error

// SupportedEnginesResponse defines model for SupportedEnginesResponse.
type SupportedEnginesResponse = []struct {
	Engine   string   `json:"engine"`
	Versions []string `json:"versions"`
}

// SyncExecutionResponse defines model for SyncExecutionResponse.
type SyncExecutionResponse struct {
	Message   *string    `json:"message,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
	Status    string     `json:"status"`
	SyncId    int64      `json:"sync_id"`
}

// SyncRuleResponse defines model for SyncRuleResponse.
type SyncRuleResponse struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Id System-assigned sync rule identifier
	Id int64 `json:"id"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

// UnprocessableEntity Standard error envelope returned for all 4xx and 5xx responses.
type UnprocessableEntity = Error

// DatabaseRequest Connection properties for a database.
type DatabaseRequest = DatabaseConnectionConfig

// SyncRuleRequest Configuration for syncing data between databases with optional masking rules.
type SyncRuleRequest = SyncRuleConfig

// ExecuteSyncRuleJSONBody defines parameters for ExecuteSyncRule.
type ExecuteSyncRuleJSONBody struct {
	// Id ID of the sync rule to execute
	Id int64 `json:"id"`
}

// AddDatabaseJSONRequestBody defines body for AddDatabase for application/json ContentType.
type AddDatabaseJSONRequestBody = DatabaseConnectionConfig

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = DatabaseConnectionConfig

// ExecuteSyncRuleJSONRequestBody defines body for ExecuteSyncRule for application/json ContentType.
type ExecuteSyncRuleJSONRequestBody ExecuteSyncRuleJSONBody

// CreateSyncRuleJSONRequestBody defines body for CreateSyncRule for application/json ContentType.
type CreateSyncRuleJSONRequestBody = SyncRuleConfig

// UpdateSyncRuleJSONRequestBody defines body for UpdateSyncRule for application/json ContentType.
type UpdateSyncRuleJSONRequestBody = SyncRuleConfig

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register an existing external database
	// (POST /databases/add)
	AddDatabase(w http.ResponseWriter, r *http.Request)
	// Create a new managed database
	// (POST /databases/create)
	CreateDatabase(w http.ResponseWriter, r *http.Request)
	// List all supported database engines and versions
	// (GET /databases/supported)
	GetSupportedEngines(w http.ResponseWriter, r *http.Request)
	// Delete a database by ID
	// (DELETE /databases/{dbID}/delete)
	DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Trigger execution of a sync rule
	// (PUT /databases/{dbID}/sync)
	ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Create a new sync rule for a database
	// (POST /databases/{dbID}/sync/init)
	CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID)
	// Delete a sync rule
	// (DELETE /databases/{dbID}/sync/{syncID}/delete)
	DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID)
	// Update an existing sync rule
	// (PUT /databases/{dbID}/sync/{syncID}/update)
	UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID)
	// Check Mezcala health
	// (GET /health)
	CheckHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register an existing external database
// (POST /databases/add)
func (_ Unimplemented) AddDatabase(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new managed database
// (POST /databases/create)
func (_ Unimplemented) CreateDatabase(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all supported database engines and versions
// (GET /databases/supported)
func (_ Unimplemented) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a database by ID
// (DELETE /databases/{dbID}/delete)
func (_ Unimplemented) DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger execution of a sync rule
// (PUT /databases/{dbID}/sync)
func (_ Unimplemented) ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new sync rule for a database
// (POST /databases/{dbID}/sync/init)
func (_ Unimplemented) CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a sync rule
// (DELETE /databases/{dbID}/sync/{syncID}/delete)
func (_ Unimplemented) DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing sync rule
// (PUT /databases/{dbID}/sync/{syncID}/update)
func (_ Unimplemented) UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check Mezcala health
// (GET /health)
func (_ Unimplemented) CheckHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AddDatabase operation middleware
func (siw *ServerInterfaceWrapper) AddDatabase(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddDatabase(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDatabase operation middleware
func (siw *ServerInterfaceWrapper) CreateDatabase(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDatabase(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupportedEngines operation middleware
func (siw *ServerInterfaceWrapper) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupportedEngines(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDatabase operation middleware
func (siw *ServerInterfaceWrapper) DeleteDatabase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDatabase(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteSyncRule operation middleware
func (siw *ServerInterfaceWrapper) ExecuteSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteSyncRule(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSyncRule operation middleware
func (siw *ServerInterfaceWrapper) CreateSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSyncRule(w, r, dbid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSyncRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	// ------------- Path parameter "syncID" -------------
	var syncID SyncID

	err = runtime.BindStyledParameterWithOptions("simple", "syncID", chi.URLParam(r, "syncID"), &syncID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "syncID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSyncRule(w, r, dbid, syncID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSyncRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSyncRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "dbID" -------------
	var dbid DbID

	err = runtime.BindStyledParameterWithOptions("simple", "dbID", chi.URLParam(r, "dbID"), &dbid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dbID", Err: err})
		return
	}

	// ------------- Path parameter "syncID" -------------
	var syncID SyncID

	err = runtime.BindStyledParameterWithOptions("simple", "syncID", chi.URLParam(r, "syncID"), &syncID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "syncID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSyncRule(w, r, dbid, syncID)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckHealth operation middleware
func (siw *ServerInterfaceWrapper) CheckHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckHealth(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/add", wrapper.AddDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/create", wrapper.CreateDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/databases/supported", wrapper.GetSupportedEngines)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/databases/{dbID}/delete", wrapper.DeleteDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/databases/{dbID}/sync", wrapper.ExecuteSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/databases/{dbID}/sync/init", wrapper.CreateSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/databases/{dbID}/sync/{syncID}/delete", wrapper.DeleteSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/databases/{dbID}/sync/{syncID}/update", wrapper.UpdateSyncRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.CheckHealth)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type DatabaseResponseJSONResponse struct {
	// Alias Optional human-friendly label
	Alias  *string `json:"alias,omitempty"`
	Engine string  `json:"engine"`
	Host   string  `json:"host"`

	// Id System-assigned unique identifier
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`

	// Path Optional filesystem path for local/embedded engines
	Path *string `json:"path,omitempty"`
	Port string  `json:"port"`

	// Role Database role for connection
	Role     *string `json:"role,omitempty"`
	SslMode  *string `json:"ssl_mode,omitempty"`
	Username string  `json:"username"`
	Version  string  `json:"version"`
}

type HealthResponseJSONResponse struct {
	Status  string  `json:"status"`
	Version *string `json:"version,omitempty"`
}

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type SupportedEnginesResponseJSONResponse []struct {
	Engine   string   `json:"engine"`
	Versions []string `json:"versions"`
}

type SyncExecutionResponseJSONResponse struct {
	Message   *string    `json:"message,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
	Status    string     `json:"status"`
	SyncId    int64      `json:"sync_id"`
}

type SyncRuleResponseJSONResponse struct {
	// DataRules Column-level anonymization rules. Keys are column names or glob-style patterns (e.g. encrypted_*). Use null to drop a column entirely.
	DataRules *map[string]string `json:"data_rules,omitempty"`

	// Exclude Table names to exclude from the sync
	Exclude *[]string `json:"exclude,omitempty"`

	// From Source database ID registered in Mezcala
	From int64 `json:"from"`

	// Id System-assigned sync rule identifier
	Id int64 `json:"id"`

	// Schemas Schemas to include in the sync
	Schemas *[]string `json:"schemas,omitempty"`

	// To Destination database ID registered in Mezcala
	To int64 `json:"to"`
}

type UnprocessableEntityJSONResponse Error

type AddDatabaseRequestObject struct {
	Body *AddDatabaseJSONRequestBody
}

type AddDatabaseResponseObject interface {
	VisitAddDatabaseResponse(w http.ResponseWriter) error
}

type AddDatabase201JSONResponse struct{ DatabaseResponseJSONResponse }

func (response AddDatabase201JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase400JSONResponse struct{ BadRequestJSONResponse }

func (response AddDatabase400JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase409JSONResponse struct{ ConflictJSONResponse }

func (response AddDatabase409JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AddDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AddDatabase500JSONResponse) VisitAddDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabaseRequestObject struct {
	Body *CreateDatabaseJSONRequestBody
}

type CreateDatabaseResponseObject interface {
	VisitCreateDatabaseResponse(w http.ResponseWriter) error
}

type CreateDatabase201JSONResponse struct{ DatabaseResponseJSONResponse }

func (response CreateDatabase201JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateDatabase400JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase409JSONResponse struct{ ConflictJSONResponse }

func (response CreateDatabase409JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateDatabase500JSONResponse) VisitCreateDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSupportedEnginesRequestObject struct {
}

type GetSupportedEnginesResponseObject interface {
	VisitGetSupportedEnginesResponse(w http.ResponseWriter) error
}

type GetSupportedEngines200JSONResponse struct {
	SupportedEnginesResponseJSONResponse
}

func (response GetSupportedEngines200JSONResponse) VisitGetSupportedEnginesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSupportedEngines500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetSupportedEngines500JSONResponse) VisitGetSupportedEnginesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDatabaseRequestObject struct {
	DbID DbID `json:"dbID"`
}

type DeleteDatabaseResponseObject interface {
	VisitDeleteDatabaseResponse(w http.ResponseWriter) error
}

type DeleteDatabase204Response struct {
}

func (response DeleteDatabase204Response) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDatabase404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteDatabase404JSONResponse) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDatabase500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteDatabase500JSONResponse) VisitDeleteDatabaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRuleRequestObject struct {
	DbID DbID `json:"dbID"`
	Body *ExecuteSyncRuleJSONRequestBody
}

type ExecuteSyncRuleResponseObject interface {
	VisitExecuteSyncRuleResponse(w http.ResponseWriter) error
}

type ExecuteSyncRule200JSONResponse struct {
	SyncExecutionResponseJSONResponse
}

func (response ExecuteSyncRule200JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response ExecuteSyncRule400JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response ExecuteSyncRule404JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ExecuteSyncRule422JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ExecuteSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ExecuteSyncRule500JSONResponse) VisitExecuteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRuleRequestObject struct {
	DbID DbID `json:"dbID"`
	Body *CreateSyncRuleJSONRequestBody
}

type CreateSyncRuleResponseObject interface {
	VisitCreateSyncRuleResponse(w http.ResponseWriter) error
}

type CreateSyncRule201JSONResponse struct{ SyncRuleResponseJSONResponse }

func (response CreateSyncRule201JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSyncRule400JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateSyncRule404JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateSyncRule500JSONResponse) VisitCreateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSyncRuleRequestObject struct {
	DbID   DbID   `json:"dbID"`
	SyncID SyncID `json:"syncID"`
}

type DeleteSyncRuleResponseObject interface {
	VisitDeleteSyncRuleResponse(w http.ResponseWriter) error
}

type DeleteSyncRule204Response struct {
}

func (response DeleteSyncRule204Response) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSyncRule404JSONResponse) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteSyncRule500JSONResponse) VisitDeleteSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRuleRequestObject struct {
	DbID   DbID   `json:"dbID"`
	SyncID SyncID `json:"syncID"`
	Body   *UpdateSyncRuleJSONRequestBody
}

type UpdateSyncRuleResponseObject interface {
	VisitUpdateSyncRuleResponse(w http.ResponseWriter) error
}

type UpdateSyncRule200JSONResponse struct{ SyncRuleResponseJSONResponse }

func (response UpdateSyncRule200JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSyncRule400JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateSyncRule404JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSyncRule500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateSyncRule500JSONResponse) VisitUpdateSyncRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealthRequestObject struct {
}

type CheckHealthResponseObject interface {
	VisitCheckHealthResponse(w http.ResponseWriter) error
}

type CheckHealth200JSONResponse struct{ HealthResponseJSONResponse }

func (response CheckHealth200JSONResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealth500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CheckHealth500JSONResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register an existing external database
	// (POST /databases/add)
	AddDatabase(ctx context.Context, request AddDatabaseRequestObject) (AddDatabaseResponseObject, error)
	// Create a new managed database
	// (POST /databases/create)
	CreateDatabase(ctx context.Context, request CreateDatabaseRequestObject) (CreateDatabaseResponseObject, error)
	// List all supported database engines and versions
	// (GET /databases/supported)
	GetSupportedEngines(ctx context.Context, request GetSupportedEnginesRequestObject) (GetSupportedEnginesResponseObject, error)
	// Delete a database by ID
	// (DELETE /databases/{dbID}/delete)
	DeleteDatabase(ctx context.Context, request DeleteDatabaseRequestObject) (DeleteDatabaseResponseObject, error)
	// Trigger execution of a sync rule
	// (PUT /databases/{dbID}/sync)
	ExecuteSyncRule(ctx context.Context, request ExecuteSyncRuleRequestObject) (ExecuteSyncRuleResponseObject, error)
	// Create a new sync rule for a database
	// (POST /databases/{dbID}/sync/init)
	CreateSyncRule(ctx context.Context, request CreateSyncRuleRequestObject) (CreateSyncRuleResponseObject, error)
	// Delete a sync rule
	// (DELETE /databases/{dbID}/sync/{syncID}/delete)
	DeleteSyncRule(ctx context.Context, request DeleteSyncRuleRequestObject) (DeleteSyncRuleResponseObject, error)
	// Update an existing sync rule
	// (PUT /databases/{dbID}/sync/{syncID}/update)
	UpdateSyncRule(ctx context.Context, request UpdateSyncRuleRequestObject) (UpdateSyncRuleResponseObject, error)
	// Check Mezcala health
	// (GET /health)
	CheckHealth(ctx context.Context, request CheckHealthRequestObject) (CheckHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AddDatabase operation middleware
func (sh *strictHandler) AddDatabase(w http.ResponseWriter, r *http.Request) {
	var request AddDatabaseRequestObject

	var body AddDatabaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddDatabase(ctx, request.(AddDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddDatabaseResponseObject); ok {
		if err := validResponse.VisitAddDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDatabase operation middleware
func (sh *strictHandler) CreateDatabase(w http.ResponseWriter, r *http.Request) {
	var request CreateDatabaseRequestObject

	var body CreateDatabaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDatabase(ctx, request.(CreateDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDatabaseResponseObject); ok {
		if err := validResponse.VisitCreateDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSupportedEngines operation middleware
func (sh *strictHandler) GetSupportedEngines(w http.ResponseWriter, r *http.Request) {
	var request GetSupportedEnginesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSupportedEngines(ctx, request.(GetSupportedEnginesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSupportedEngines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSupportedEnginesResponseObject); ok {
		if err := validResponse.VisitGetSupportedEnginesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDatabase operation middleware
func (sh *strictHandler) DeleteDatabase(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request DeleteDatabaseRequestObject

	request.DbID = dbid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDatabase(ctx, request.(DeleteDatabaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDatabase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDatabaseResponseObject); ok {
		if err := validResponse.VisitDeleteDatabaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExecuteSyncRule operation middleware
func (sh *strictHandler) ExecuteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request ExecuteSyncRuleRequestObject

	request.DbID = dbid

	var body ExecuteSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExecuteSyncRule(ctx, request.(ExecuteSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExecuteSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExecuteSyncRuleResponseObject); ok {
		if err := validResponse.VisitExecuteSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSyncRule operation middleware
func (sh *strictHandler) CreateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID) {
	var request CreateSyncRuleRequestObject

	request.DbID = dbid

	var body CreateSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSyncRule(ctx, request.(CreateSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSyncRuleResponseObject); ok {
		if err := validResponse.VisitCreateSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSyncRule operation middleware
func (sh *strictHandler) DeleteSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	var request DeleteSyncRuleRequestObject

	request.DbID = dbid
	request.SyncID = syncID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSyncRule(ctx, request.(DeleteSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSyncRuleResponseObject); ok {
		if err := validResponse.VisitDeleteSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSyncRule operation middleware
func (sh *strictHandler) UpdateSyncRule(w http.ResponseWriter, r *http.Request, dbid DbID, syncID SyncID) {
	var request UpdateSyncRuleRequestObject

	request.DbID = dbid
	request.SyncID = syncID

	var body UpdateSyncRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSyncRule(ctx, request.(UpdateSyncRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSyncRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSyncRuleResponseObject); ok {
		if err := validResponse.VisitUpdateSyncRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckHealth operation middleware
func (sh *strictHandler) CheckHealth(w http.ResponseWriter, r *http.Request) {
	var request CheckHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckHealth(ctx, request.(CheckHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckHealthResponseObject); ok {
		if err := validResponse.VisitCheckHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/juBH+KwRb4NpCfkk2e4f6Wzb29ozbS9K8FGi3i4AWxzbvKFJHUol1gf97MaQk",
	"S5a8cbzeRVH0y64jkcPhMzPPDId6prFOUq1AOUtHzzRlhiXgwPi/+Gw69v+DjY1IndCKjui9Er9lQAQH",
	"5cRcgCF6TtwSCGeOzZgFGlGBA1PmljSiiiVAR0FYRA38lgkDnI6cySCiNl5CwnAVWLEklUBHZ6cRnWuT",
	"MEdHVCj3/RmNqMtTCH/CAgxdryNqcxW/SkGcQEwmd2hYyNtLxx/2UXEdRIF17zQX4DEdFyDdhBf4KNbK",
	"gfI/WZpKETPcyOAXi7t5rq3+RwNzOqJ/GGyMNghv7aCUe6GVghgFXGg1F4ugRhOga5ZLzTiZa0MMLIR1",
	"YIRaEG1IbIA5/M0qc5K4EtlvgbOO6G2u4ptMHn1Hpdz99lEprg3JUl5uojJ5h+rePDbVygbTvGN8/z1U",
	"noAjOdr93fn44Wby9/vJ7R2NaALWsgU+fy9AcvIdqIVQ8B0RlpR69Ok62hOMiTHadGFwtwRSOBmKTphE",
	"vwSOOMyZkJY8Mik4C+ZbRxThlCI+bI8XV5fvP0wvmhs837jKk3BL4pbCEowpwqQBxnMCK2GdPd52rc5M",
	"vC0ed/wotGQOLGEk8yygwFp0YOsME8p5FTYhGIz/Ko9lUl7N6ejjodEYPdPU6BSMKwhB8DaD3ebWQdJj",
	"1oqFAl7spcZoNHo9XW68/yMu+qkapGe/QOzo+tMOvH1oBY8q2QL4xuYGYm2CL/8ITLrlQbg2QbGOucz/",
	"KnS0DhkK13gEY8WWf9KT/mn/zWbb5eitXRdS2ztv7/sWzKOIIUQri5dsJoEwxYmBVBtniXCWxJkxoBwJ",
	"cj0CU+XAKCZxPpjgxocE2vTybnJzef7h4XZy84/JzcPk5ubqphl1imQKVinEaBvAlYiOvUq8T64loG2c",
	"yQlbMKEIhoU5RgQ217V+nz0rOGzrgGtdavdeZ4ofhMHl1d3D+6v7y3Fj3+MtrgGyEI+gyHRMnpglSjsy",
	"xyWPTK7AN7zDNYSFPPH4hW6zFP0C+MTTvD0oBoSDxLaDIWSOpsOn2rqFAdv2+SpCbGPGR3qCvHDyFv/5",
	"HmOgWq0loHjAjGF5K4gKbWrLtOOpJaLtRfgC6zJbArchlLCC9eHmliAMYY9MSB+C5aIB9FzFkxXEGQo9",
	"AutUTlZHGhchQgknPAnaLI7B2nkmZd4FvnUMd/PAXFPM6fD0rDf8vjc8uTs5HQ2Ho+HwX7RG3Jw56DmR",
	"wA6hu+gQC5yHkENeV5xuUWMhJnoNSd6AzaTz1bURi0UoIms1F4HSOJW5QqH41fLuds14ULbd6N+dcH/4",
	"dvnWV7J1lTyQ9yo1Gr0QQ2KinHD5QQR7f3l9c3Uxub09f/dh8jC5vJve/bPBtbdFnaU44WCdUF5iFamW",
	"xEwhD84gnK9YAl+hpn0CKXtFVTvLHJZzjglliYWEKSfikHmQE6q1G2etVhXWcoHNCLLxF3+u2JyD8ATR",
	"dCYmRVioKezK/2CSLLOEqd7cCFBc5kSyGci6I6E43uOzrpB/Lekvtd1iHD7rF3/0Y510zQnn3vqcJO/V",
	"TvGtCSmz9kmbJttQ+yY2b1ydzKpxnTLc8jOYzYUE6wOS4EhvA6ljJgeQzIBzrHVCfmggOXhkZiDFbJDk",
	"3Xhikmmq/fbszWnXSKNDkDQVrMoOfB1OnJXPNDTBI4lWO5KDlQ+Jj73nxgxPFF0TMovV5LaVGE+E+kzm",
	"36qN375YGPslolZqp4VbFejV1Km5Qlf2r+reLaJ1THFmymoV1CNInWKsu8wg8/qAk5KcrVaedN6uVqQ6",
	"orfjLy6gbK7yM4uXQkEPDeFrhrCaH1w3VL28bCHJweHh2Uc55yI453Vt9dAZ2uHEmymerGDlCJvpzHmW",
	"9OrQDtRq5UdT7o+eR6r91F6Wna1S5mZ3O0rXrRL5JccoQCs167L1Vsrtota5WGQmpA60MCYzrBSQacgM",
	"3BNAPaf4ul6XUCbM/oqDMfl1uABOe/Dvdpvqucu8TRVllqiehEeQhCmt8kT8HvQNy5KfILeEGSCxH+q7",
	"G77hsJB61rMul4B0hWc/S/4E/UWfgIpNnmIp+Jc/98m9BaIyKYnThBudElaKwgrDgMz7/27wyDOFhAmJ",
	"/nx++9Nk7MOzkkhHKGzdYQ5YxTLrCos77ztBcadJMY7MjU6q5mhdgY+UZVy4B6kXPuFAkj4g2q85OkQU",
	"xXcQQXGOKjl1Oq53FoQiP8PvMZOsrs/JHlVXI/tzmLNMOtxJms2kiFHzLT3CaMRDqICHUDvQKGRElCkm",
	"cydi+zoknO5IKh1F1V5gHNDy8ZbwanSX9kLNOzQ8v576mE2YYosyaEOcPgpWquaJRDhPPMUjcn49rWWS",
	"ER32h/0TBEKnoFgq6Ii+6Q/7ZzSUBB7EQSV9wLivMtKirMFo9jhNOWrF+XhTpmx67PmukrPRhh9s9+C3",
	"G8Gnw5Pdgopxg1YXcR3Rs+Hw5Ym1NrOf8teXp1Q923VE3+6zRlcbyhfHWZIwk/uzW3AxwlRoY6BxYRWm",
	"1a9yHFtY9J/KNPQTSqqZKpxXdlvrwr//v8G+zGABRcKIgqcQjrWeyV52qlotqM4COiz1N3DbjSzagnqP",
	"3ezshh0Pjg/COl8rvtBAqrpU+yD0zGfT8XrAQYIrUmj5qwnU2D+vuXT94nRHj2IzZODvQtefWtCefebc",
	"EVTZakB5fzx7Gc+qD3s8AwQI6veEs5z469O9cfZJFmkj6/DF0NiDsrz8EowbbHNgb7CrcTQdt26WQ2nl",
	"Nf8aLaN2r2RatqgseVqKeNmpSue97QFh3dlvPZRGX+m2Z6enL0/o6owdz+XvQpdz09ZE87PGZwXbvt/z",
	"Pv4Z/x8IJdxLufPoQfByyt2+1T8o5bY6vt/IV75Gyt3EVbMteJDRn8O3Jvunmi/0gOjFccXHL/slpdsK",
	"i//arPRlQVnZJzTgdyape//62xrn6IE8/J8P5GCmxlFnX/9Y+k8adlbMF0uIfw2fPRxUKW99MXFE7kLF",
	"yvM5WZYallstHoQrqHCJHzw2M5KO6NK51I4Gg6Q43ytwAzyzowcWIp5bl4HhQBkV91eRL7/DQaXrWzLf",
	"zCu/DawqRQyG7v5huIYqLho35rPtDmKH4GDRtvDyM48Ah1+huGsWUri8JqkAbP1p/Z8AAAD//9xESH00",
	"KQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
